- common/util.go
- docs/en_US/rules/sinks/mqtt.md
- docs/en_US/rules/sources/mqtt.md
- etc/mqtt_source.yaml
- xsql/processors/xsql_processor.go
- xstream/extensions/mqtt_source.go
- xstream/extensions/mqtt_source.yaml
- xstream/sinks/mqtt_sink.go
add cert & key support for mqtt sink.
> add cert & key support

- Makefile
- xstream/cli/main.go
- xstream/server/main.go
Add version info in source file and make file.
> add version info. close #10

- etc/sources/zmq.yaml
- go.mod
- plugins/sinks/zmq.go
- plugins/sources/zmq.go
The zeromq source and sink are implemented as extension/plugin. Need to check if the dependency for zmq4 in go.mod is required.
> zeromq source and sink

- common/util.go
- etc/sources/random.yaml
- plugins/functions/countPlusOne.go
- plugins/sinks/file.go
- plugins/sources/zmq.go
- xsql/ast.go
- xsql/funcs_aggregate.go
- xsql/functions.go
- xsql/processors/extension_test.go
- xstream/extensions/mqtt_source.go
ast: check aggregate for custom functions
extension functions should not use all lower name for search
update plugins for the mod name change
update file sink to only write to file when some data has received
> bug(extension): agg function does not called successfully

- Makefile
- plugins/sinks/file.go
fix plugin build & file sink issue
> fix plugin build & file sink issue

- common/templates/funcs.go
- docs/en_US/rules/sinks/rest.md
- docs/zh_CN/rules/sinks/rest.md
- xstream/sinks/rest_sink.go
- xstream/sinks/rest_sink_test.go
- add dataTemplate property
- modify bodyType property
- configuration bug fix
- add unit test
- modify docs
> Add dataTemplate to rest sink

- deploy/chart/kuiper/README_zh.md
- deploy/docker/README.md
- deploy/docker/docker-entrypoint.sh
+ Fix #53 
+ Update chart readme，now helm repo is ready to use
> Fix #53 and update chart readme

- common/util.go
- xsql/processors/xsql_processor.go
- xstream/api/stream.go
- xstream/contexts/default.go
- xstream/nodes/sink_node.go
- xstream/server/server/server.go
- xstream/streams.go
print err info for query tools
> print err info for query tools

- xstream/extensions/mqtt_source.go
- xstream/sinks/mqtt_sink.go
Re-connect to server if the connection is drop.
> fix mqtt connection reconnect problem

- xstream/operators/window_op.go
- xstream/sinks/rest_sink.go
1) Not to lower case the URL, otherwise 404 could be found if an upper case URL is specified.
2) Multiple error handling
3) Detecting server when opening sink
4) Add response code detection
> Rest sink issue

- common/util.go
- docs/en_US/operation/configuration_file.md
- docs/zh_CN/operation/configuration_file.md
- etc/kuiper.yaml
- xstream/nodes/prometheus.go
- xstream/nodes/sink_node.go
- xstream/nodes/source_node.go
- xstream/nodes/stats_manager.go
- xstream/operators/operations.go
- xstream/operators/window_op.go
- xstream/server/server/server.go
Export metrics to Prometheus and allow to disable it by configuration.
> Prometheus

- .github/workflows/release.yaml
- .github/workflows/script/upload_github_release_asset.sh
Add sha256 validation when building and publishing packages
> Add sha256 validation when building and publishing packages

- plugins/sources/random.go
- plugins/sources/zmq.go
- xstream/api/stream.go
- xstream/extensions/mqtt_source.go
- xstream/nodes/source_node.go
- xstream/test/mock_source.go
Add an error callback so that the source can communicate with the rule for errors during execution
> api change for source

- common/kv.go
- common/util.go
- common/util_test.go
- xstream/server/server/rpc.go
- xstream/server/server/ruleManager.go
- xstream/server/server/server.go
#97 
To enable the concurrent creation of rules in order for massive rule creation testing
> Concurrent access

- xstream/server/server/server.go
Update the log message for startup.
> add log info

- .github/workflows/release.yaml
- Dockerfile-by-corss-build
Fix https://github.com/emqx/kuiper/issues/116
> Fix workflows

- .github/workflows/build_packages.yaml
- deploy/docker/Dockerfile
+ Update Dockerfile
+ Add docker build for workflows
> Update docker and workflows

- fvt_scripts/edgex/valuedesc/vd_server.go
- fvt_scripts/start_vdmock.sh
> move vd file location

- xsql/ast.go
- xsql/lexical.go
- xsql/plans/aggregate_operator.go
- xsql/plans/aggregate_test.go
- xsql/plans/filter_operator.go
- xsql/plans/filter_test.go
- xsql/plans/having_operator.go
- xsql/plans/having_test.go
- xsql/plans/join_operator.go
- xsql/plans/join_test.go
- xsql/plans/order_operator.go
- xsql/plans/order_test.go
- xsql/plans/preprocessor.go
- xsql/plans/preprocessor_test.go
- xsql/plans/project_operator.go
- xsql/plans/project_test.go
- xsql/plans/str_func_test.go
- xsql/processors/xsql_processor_test.go
- xsql/valuer_eval_test.go
- xstream/nodes/sink_node.go
- xstream/operators/operations.go
- xstream/operators/watermark.go
- xstream/operators/window_op.go
> Schemaless and stream error handling support

- docs/en_US/sqls/data_types.md
- docs/en_US/sqls/streams.md
- docs/en_US/sqls/windows.md
- xsql/ast.go
- xsql/funcs_aggregate.go
- xsql/plans/having_operator.go
- xsql/plans/having_test.go
- xsql/plans/project_test.go
- xsql/processors/xsql_processor_test.go
- xstream/nodes/source_node.go
- xstream/nodes/with_edgex.go
- xstream/nodes/without_edgex.go
> Schemaless bugs and docs

- .github/workflows/fvt_tests.yaml
- Makefile
- README-CN.md
- README.md
- deploy/docker/Dockerfile
- fvt_scripts/run_jmeter.sh
- xstream/extensions/edgex_source.go
- xstream/nodes/with_edgex.go
- xstream/nodes/without_edgex.go
+ Run `make` compilation kuiper with out edgex
+ Run `make build_with_edgex` compilation kuiper with edgex
+ The docker image introduces edgex by default
+ Update actions
> Add build tags

- docs/en_US/rules/overview.md
- docs/en_US/rules/sources/edgex.md
- fvt_scripts/README.md
add docs for edgex source and test script
> add docs for edgex source and test script

- xsql/ast.go
- xsql/funcs_aggregate.go
- xsql/funcs_ast_validator.go
- xsql/funcs_ast_validator_test.go
- xsql/funcs_misc.go
- xsql/functions.go
- xsql/parser.go
- xsql/plans/aggregate_test.go
- xsql/plans/filter_test.go
- xsql/plans/misc_func_test.go
- xsql/plans/project_test.go
- xsql/processors/xsql_processor_test.go
- xstream/test/mock_source.go
> Support for generic meta function

- fvt_scripts/edgex/pub.go
- fvt_scripts/run_jmeter.sh
- fvt_scripts/select_edgex_meta_rule.jmx
> add metadata script

- xstream/nodes/sink_node.go
> Reduce default cache length to 1024

- deploy/chart/kuiper/templates/StatefulSet.yaml
- deploy/chart/kuiper/templates/sevice.yaml
- deploy/chart/kuiper/values.yaml
- deploy/docker/Dockerfile
+ Add port for docker
+ Add service port for helm chart
> Update prot for container

- xsql/ast.go
- xsql/plans/project_test.go
A fix for https://github.com/emqx/kuiper/issues/166.
> Json expr issue

- xstream/server/server/rest.go
The fix for https://github.com/emqx/kuiper/issues/163
> add root handler for restapi

- xsql/funcs_misc.go
- xsql/functions.go
- xsql/plans/misc_func_test.go
- xsql/plans/preprocessor.go
- xsql/plans/preprocessor_test.go
- xsql/plans/project_test.go
> Nullable support

- .github/workflows/run_fvt_tests.yaml
- deploy/chart/kuiper/templates/StatefulSet.yaml
Add readinessProbe on helm chart in then https://github.com/emqx/kuiper/issues/163  after
> Add readiness probe on helm chart

- docs/en_US/rules/sinks/mqtt.md
- xstream/sinks/mqtt_sink.go
Support the conf required by HW IEF.
> Add insecureSkipVerify conf

- go.mod
> upgrade edgex lib versions

- xsql/ast.go
- xsql/processors/xsql_processor.go
- xsql/util.go
- xstream/server/server/rest.go
> feat(rest): print the field type string for desc stream

- fvt_scripts/edgex/pub.go
- fvt_scripts/edgex/valuedesc/vd_server.go
- fvt_scripts/select_edgex_condition_rule.jmx
- xsql/plans/preprocessor.go
- xstream/extensions/edgex_source.go
- xstream/extensions/edgex_source_test.go
Fix for https://github.com/emqx/kuiper/issues/223
> fix for #223

- docs/en_US/cli/rules.md
- docs/en_US/restapi/rules.md
- docs/zh_CN/cli/rules.md
- fvt_scripts/rule_test.jmx
- xsql/processors/xsql_processor.go
- xstream/server/server/rest.go
- xstream/server/server/rpc.go
- xstream/server/server/ruleManager.go
> feat(rules): show rules return brief status

- .github/workflows/run_fvt_tests.yaml
- .github/workflows/run_test_case.yaml
- fvt_scripts/plugin_end_2_end.jmx
- fvt_scripts/plugins/pub/zmq_pub.go
- fvt_scripts/plugins/service/server.go
- fvt_scripts/plugins/zmq.yaml
- fvt_scripts/prepare_plugins.sh
- fvt_scripts/run_jmeter.sh
- fvt_scripts/setup_env.sh
- plugins/manager.go
Add an FVT script for plugin case.
> Plugin rule

- xsql/plans/aggregate_operator.go
- xsql/plans/aggregate_test.go
- xsql/plans/having_operator.go
- xsql/plans/having_test.go
- xsql/plans/order_test.go
- xsql/plans/preprocessor.go
- xsql/plans/project_operator.go
- xsql/plans/project_test.go
- xsql/processors/xsql_processor.go
- xsql/processors/xsql_processor_test.go
> Aggregate alias

- .github/workflows/run_fvt_tests.yaml
- xstream/nodes/sink_cache.go
- xstream/nodes/sink_node.go
> bug(stream): fix sink infinite resend after rule stopped problem

- .github/workflows/build_packages.yaml
- deploy/docker/Dockerfile
* fix(docker): fix path error
* test(docker): fix test error
> fix(docker): fix path error (#290)

- docs/en_US/sqls/built-in_functions.md
- docs/zh_CN/sqls/built-in_functions.md
- xsql/funcs_aggregate.go
- xsql/plans/project_test.go
> Ignore null values in aggregate func calculations.

- fvt_scripts/change_rule_status.jmx
- xstream/server/server/ruleManager.go
> bug(rule): get rule state error for runtime invalid rule

- deploy/docker/Dockerfile
- deploy/docker/Dockerfile-alpine
- deploy/docker/Dockerfile-slim
- deploy/docker/conf_util.go
- deploy/docker/conf_util_test.go
> change to original type value

- plugins/manager.go
> bug(plugin): plugin manager initialization should stop for errors

- docs/CONTRIBUTING.md
> docs(file): Add contributing doc

- docs/en_US/plugins/plugins_tutorial.md
- docs/zh_CN/plugins/plugins_tutorial.md
> feat(doc): update plugin tutorial for export symbol

- docs/en_US/plugins/plugins_tutorial.md
- docs/zh_CN/plugins/plugins_tutorial.md
> feat(doc): add more description for plugin compile and test

- common/templates/funcs.go
- common/templates/funcs_test.go
- docs/en_US/edgex/edgex_rule_engine_tutorial.md
- docs/en_US/rules/data_template.md
- docs/en_US/rules/overview.md
- docs/zh_CN/edgex/edgex_rule_engine_tutorial.md
- docs/zh_CN/rules/data_template.md
- docs/zh_CN/rules/overview.md
- xstream/nodes/sink_node.go
1. Detailed docs for data templates and related docs
2. Add functions support in data templates
> feat(templates): several fixes for sink data templates

- xstream/server/server/server.go
Http server shutdown can close the service after all connections are executed.
> feat(main): gracefully shut down restful  rpc  prometheus services

- go.mod
- xstream/server/server/rest.go
> fix(rest): support CORS

- .github/workflows/build_packages.yaml
Done https://github.com/emqx/kuiper/issues/422
> chore:add multi-platforms for kubernetes tools

- plugins/sinks/file.json
- plugins/sinks/influxdb.json
- plugins/sinks/taos.json
- plugins/sinks/zmq.json
Added `about` section in metadata.
> meta: add about section in metadata

- xsql/processors/xsql_processor.go
> Validate sql before saving rule during rule creation

- xstream/nodes/source_node.go
> fix(source): panic when enable debug for source

- docs/en_US/extension/overview.md
- plugins/manager.go
#444 
Now support both @1.0.0 and @v1.0.0
> feat(plugin): plugin version convention change

- plugins/manager.go
- plugins/sinkMeta.go
- plugins/sourceMeta.go
> feat():metadata file path

- docs/en_US/sqls/built-in_functions.md
- docs/zh_CN/sqls/built-in_functions.md
- xsql/ast.go
- xsql/funcs_aggregate.go
- xsql/funcs_ast_validator.go
- xsql/funcs_ast_validator_test.go
- xsql/functions.go
- xsql/parser.go
- xsql/parser_test.go
- xsql/plans/project_operator.go
- xsql/plans/project_test.go
- xsql/processors/window_rule_test.go
> feat(function): add aggregate function deduplicate

- xstream/nodes/dynamic_channel_buffer.go
limit field in DynamicChannelBuffer seems to be not thread-safe
> feat: wrap limit in DynamicChannelBuffer with atomic

- .ci/Dockerfile-plugins
- .github/workflows/build_packages.yaml
- Makefile
Done https://github.com/emqx/kuiper/issues/536
> chore(CI): build taos plugins

- xstream/extensions/edgex_source.go
- xstream/sinks/edgex_sink.go
Fix for [issue](https://github.com/emqx/kuiper/issues/549).
> feat: add redisstream message bus #549

- etc/sinks/edgex.json
> fix: the help doc for edgex

- Makefile
Signed-off-by: zhanghongtong <rory-z@outlook.com>
> chore(build): fix build error on 386

- xstream/nodes/dynamic_channel_buffer.go
> fix(node): fix dynamic channel buffer error in arm

- docs/en_US/edgex/edgex_rule_engine_tutorial.md
- docs/zh_CN/edgex/edgex_rule_engine_tutorial.md
> docs: update edgex tutorial

- xsql/processors/common_test.go
- xsql/processors/xsql_processor.go
- xstream/nodes/sink_cache.go
- xstream/nodes/sink_node.go
1. Do not return error message when stop query
2. Refactor disable sink cache to not create cache at all
3. Test case refactor to be more stable.
> Cli query related change

- docs/en_US/restapi/overview.md
- docs/zh_CN/restapi/overview.md
- xstream/server/server/rest.go
Add a ping api for keep-alive detection #626
> feat(ping):Add a ping api for keep-alive detection #626

- .github/workflows/build_packages.yaml
- Makefile
- docs/en_US/plugins/functions/functions.md
- docs/zh_CN/plugins/functions/functions.md
- etc/functions/geohash.json
- etc/functions/image.json
- plugins/funcMeta.go
- plugins/functions/geohash/geohash.go
Hope the system can provide GeoHash function #647
> Add geohash function plugin

- docs/en_US/edgex/edgex_rule_engine_tutorial.md
Added a missing quote in Create Rule - Option 1 code
> Added a missing quote in edgex_rule_engine_tutorial.md

- docs/en_US/sqls/lexical_elements.md
- docs/en_US/sqls/query_language_elements.md
- docs/zh_CN/sqls/lexical_elements.md
- docs/zh_CN/sqls/query_language_elements.md
- xsql/ast.go
- xsql/funcs_ast_validator.go
- xsql/lexical.go
- xsql/parser.go
- xsql/parser_test.go
- xsql/processors/rule_test.go
- xsql/valuer_eval_test.go
- xstream/operators/aggregate_test.go
- xstream/operators/project_test.go
> Support case expression

- README-CN.md
- README.md
Display effect like [this](https://github.com/Swilder-M/kuiper/tree/readme-icon)
> fix(README.md): add icon to readme file

- docs/en_US/sqls/query_language_elements.md
- etc/sinks/mqtt.json
- Fix for 2 MQTT labels in `mqtt.json`
- Fix for broken links in documentation for Query Language Elements
> Fix labels and broken links

- fvt_scripts/change_stream_rule.jmx
- fvt_scripts/change_stream_rule.txt
- go.mod
- xsql/ast.go
- xsql/funcs_ast_validator_test.go
- xsql/parser.go
- xsql/parser_test.go
- xstream/operators/project_operator.go
- xstream/planner/dataSourcePlan.go
- xstream/planner/planner.go
- xstream/planner/planner_test.go
- xstream/planner/util.go
- xstream/topotest/window_rule_test.go
> fix(join): problem when joining without stream name in fieldRef

- common/message_util_test.go
- common/util.go
- common/util_test.go
- plugins/manager.go
- services/manager.go
- services/schema.go
- xstream/extensions/file_source.go
- xstream/operators/preprocessor_test.go
- xstream/server/server/ruleManager.go
- xstream/server/server/server.go
- xstream/topotest/mock_topo.go
> fix(common): fix problems when accessing sub-folder for absolute path

- xsql/processors/stream_processor_test.go
- xsql/util.go
for streams with multiple levels of embeded structs
#792
> fix(stream): describe stream error

- docs/en_US/cli/rules.md
- docs/en_US/cli/streams.md
- docs/en_US/restapi/plugins.md
- docs/en_US/restapi/rules.md
- docs/en_US/restapi/services.md
- docs/en_US/streams.md
- docs/zh_CN/cli/rules.md
- docs/zh_CN/cli/streams.md
- docs/zh_CN/restapi/plugins.md
- docs/zh_CN/restapi/rules.md
- docs/zh_CN/restapi/services.md
- docs/zh_CN/streams.md
1. cli create stream/rule json string must be quoted
2. REST samples, default port must be 9081
#802
> fix(doc): fix problems of CLI and REST API port

- xstream/server/server/ruleManager.go
Do not return all as error
#707
> fix(manager):get rules should return error status as state #707

- xstream/nodes/sink_node.go
- xstream/nodes/sink_node_test.go
> test(node):add more tests for data template

- plugins/sinkMeta.go
- plugins/sinkMeta_test.go
- plugins/sourceMeta.go
- plugins/sourceMeta_test.go
> fix(meta):do not share base properties across sinks

- deploy/chart/kuiper/Chart.yaml
> build(*): update helm chart version

- xsql/ast.go
- xstream/operators/filter_test.go
> fix(sql): support short-circuit for logical operation

- xsql/lexical.go
- xsql/parser.go
- xsql/parser_test.go
> fix(sql): subtraction was parsed as negative number

- xstream/topotest/window_rule_test.go
#778 
Signed-off-by: ngjaying <ngjaying@gmail.com>
> test(sql): test case for join alias

- xstream/topotest/window_rule_test.go
#839 
Signed-off-by: ngjaying <ngjaying@gmail.com>
> test(sql): test case for alias name clash

- xstream/planner/analyzer.go
- xstream/planner/analyzer_test.go
- xstream/planner/planner_test.go
if only one stream exists.
Also add unit test case for schemaless streams
Signed-off-by: ngjaying <ngjaying@gmail.com>
> fix(planner): schemaless stream name default to the stream

- internal/pkg/tskv/sqlite.go
- internal/pkg/tskv/sqlite_test.go
- internal/pkg/tskv/tskv.go
- internal/topo/checkpoint/coordinator.go
- internal/topo/state/kv_store.go
- internal/topo/state/kv_store_test.go
- internal/topo/state/memory_store.go
- pkg/api/stream.go
Clean checkpoint of 
- storage in memory, actively clean
- completed checkpoint in db. Clean periodically in batch to avoid frequent IO
> Checkpoint clean up

- docs/en_US/plugins/plugins_tutorial.md
- docs/zh_CN/plugins/plugins_tutorial.md
update plugin tutorial for english version
> update plugin tutorial 

- .github/workflows/build_packages.yaml
- tools/kubernetes/README-CN.md
- tools/kubernetes/README.md
- tools/kubernetes/conf/conf.go
- tools/kubernetes/etc/cf.yaml
Add two options in etc/cf.yaml file for log print
* consoleLog: true/false
* fileLog: true/false
Closes: #905 
> feat(tool): for ekuiper kubernetes tool, add options for log print location

- docs/en_US/plugins/sinks/redis.md
- docs/zh_CN/plugins/sinks/redis.md
- etc/sinks/redis.json
docs(sink redis): Add redis sink document
> Add redis sink document

- internal/xsql/collections.go
> fix(*): remove unnecessary console log print

- .github/workflows/build_packages.yaml
Fix https://github.com/lf-edge/ekuiper/issues/940
> chore(CI): upload artifact to aws s3 when create release

- Makefile
Signed-off-by: wfnuser <wfnuser@126.com>
> style: missing blank space in makefile

- internal/topo/planner/planner_test.go
- pkg/ast/visitor.go
> fix(valuer): visitor should visit index expression

- docs/en_US/rules/sinks/edgex.md
- docs/zh_CN/rules/sinks/edgex.md
- internal/topo/sink/edgex_sink.go
The profile name must be in front of device name.
Closes: #947
> fix(edgex): fix wrong topic format

- docs/en_US/sqls/query_language_elements.md
- docs/zh_CN/sqls/query_language_elements.md
- internal/topo/planner/planner.go
> doc(sql): clear description for join/group by

- internal/topo/sink/rest_sink.go
> fix(sink): rest sink should close body

- internal/topo/operator/aggregate_test.go
- internal/topo/operator/join_multi_test.go
- internal/topo/operator/project_test.go
> test(ut): add more multi full join case

- docs/en_US/operation/configuration_file.md
- docs/zh_CN/operation/configuration_file.md
- etc/kuiper.yaml
- internal/conf/conf.go
- internal/pkg/store/setup.go
Due to CI and other tools' requirement
> fix(store): the db path must be fixed

- internal/topo/source/mqtt_source.go
> fix(source): mqtt source should stop executing after errors

- etc/sinks/tdengine.json
> docs(plugin): fix typo in etc/sinks/tdengine.json helpUrl

- .github/workflows/run_fvt_tests.yaml
- extensions.mod
- extensions.sum
- go.mod
- go.sum
- internal/pkg/jwt/jwt_rsa.go
- internal/pkg/jwt/rsa_keys.go
- internal/topo/source/httppull_source.go
> fix(jwt): replace the archieve jwt dependency

- sdk/python/ekuiper/runtime/function.py
> fix(portable): fix python function runtime incorrect running status

- cmd/kuiper/main.go
- extensions/sources/random/random.go
- internal/binder/factory.go
- internal/binder/function/binder.go
- internal/binder/function/funcs_agg.go
- internal/binder/function/funcs_ast_validator.go
- internal/binder/function/funcs_misc.go
- internal/binder/function/function.go
- internal/binder/mock/mock_factory.go
- internal/conf/load.go
- internal/pkg/jwt/rsa_keys.go
- internal/plugin/native/manager.go
- internal/plugin/portable/factory.go
- internal/server/rest.go
- internal/service/manager.go
- internal/topo/operator/field_processor.go
- internal/topo/operator/preprocessor.go
- internal/topo/operator/preprocessor_test.go
- internal/topo/planner/analyzer.go
- internal/topo/planner/dataSourcePlan.go
- internal/topo/planner/planner_test.go
- internal/topo/source/edgex_source.go
- internal/topo/source/mqtt_type.go
- internal/xsql/collections.go
- internal/xsql/parser.go
- internal/xsql/parser_test.go
- sdk/go/example/mirror/random_source.go
Remove the usage of strings.lowercase as most as possible to boost performance
> Refactor: remove strings.lowercase

- internal/server/ruleManager.go
> fix(topo): return error message for get status

- internal/topo/sink/edgex_sink.go
- internal/topo/sink/edgex_sink_test.go
- Explicitly warn un-support of data template
- Remove json unmarshal from the sink node
> refactor(edgex): edgex sink to deal with map directly

- internal/topo/planner/analyzer.go
- internal/topo/planner/analyzer_test.go
> fix(planner): add validation for stream name of field ref

- .github/workflows/run_fvt_tests.yaml
- etc/sources/edgex.yaml
- test/README.md
- test/edgex/pub.go
- test/edgex/sub/sub.go
- test/edgex_redis_share_connection_sink_rule.jmx
- test/redis/set.go
- test/redis_kv_storage.jmx
- test/run_jmeter.sh
- test/setup_env.sh
> test(fvt): add edgex and KV store for redis test

- docs/en_US/sqls/data_types.md
- docs/zh_CN/sqls/data_types.md
> fix(doc): correct data comparison table

- .github/workflows/run_fvt_tests.yaml
- docs/en_US/rules/sources/mqtt.md
- docs/zh_CN/rules/sources/mqtt.md
- etc/mqtt_source.json
- etc/sinks/edgex.json
- etc/sinks/mqtt.json
- etc/sources/edgex.json
- internal/meta/connectionMeta.go
- internal/meta/connectionMeta_test.go
- internal/meta/sinkMeta.go
- internal/meta/sourceMeta.go
- internal/meta/yamlConfigMeta.go
- internal/meta/yamlConfigMeta_test.go
- internal/meta/yaml_config_ops.go
- internal/meta/yaml_config_ops_test.go
- internal/server/rest.go
- internal/topo/source/httppull_source.go
> fea(meta): backend support for share connection feature

- docs/en_US/operation/configuration_file.md
- docs/zh_CN/operation/configuration_file.md
- internal/conf/conf.go
- internal/conf/connect_selector.go
- internal/conf/redis_store_config.go
- internal/conf/redis_store_config_test.go
- internal/topo/connection/client_edgex.go
- internal/topo/connection/client_edgex_test.go
- internal/topo/connection/client_mqtt.go
- internal/topo/connection/client_mqtt_test.go
- internal/topo/connection/client_wrapper.go
- internal/topo/connection/connect_selector_test.go
- internal/topo/connection/manager.go
- internal/topo/connection/manager_test.go
> fea(store): support connection info reuse in edgex redis for kv storage

- docs/en_US/extension/native/sink.md
- docs/zh_CN/extension/native/sink.md
- extensions/sinks/file/file.go
- extensions/sinks/redis/redis.go
- extensions/sinks/zmq/zmq.go
- internal/plugin/portable/runtime/sink.go
- internal/topo/context/default_test.go
- internal/topo/context/transform.go
- internal/topo/node/sink_node.go
- internal/topo/sink/mqtt_sink.go
- internal/topo/sink/rest_sink.go
- internal/topo/sink/rest_sink_test.go
- internal/topo/topotest/mocknode/mock_sink.go
- pkg/api/stream.go
Do not save the data value each time or it would not be released
> fix(context): context transform api change

- docs/en_US/edgex/edgex_rule_engine_tutorial.md
- docs/en_US/rules/sinks/edgex.md
- docs/zh_CN/edgex/edgex_rule_engine_tutorial.md
- docs/zh_CN/operation/configuration_file.md
- docs/zh_CN/rules/sinks/edgex.md
- docs/zh_CN/rules/sinks/mqtt.md
- docs/zh_CN/rules/sources/edgex.md
- docs/zh_CN/rules/sources/mqtt.md
- etc/connections/connection.yaml
> docs(edgex): add readme for connection reuse for edgex jakarta

- docs/en_US/sqls/data_types.md
- docs/zh_CN/sqls/data_types.md
> fix(doc): fix md table syntax error

- docs/en_US/edgex/edgex_rule_engine_tutorial.md
- docs/zh_CN/edgex/edgex_rule_engine_tutorial.md
> fix(docs): unsecure edgeX redis remove password config

- internal/plugin/portable/runtime/connection.go
- internal/plugin/portable/runtime/sink.go
- internal/plugin/portable/runtime/source.go
- sdk/go/runtime/sink.go
Source stop should be triggerred explicitly by close
> fix(portable): source/sink clean up

- docs/en_US/rules/sinks/rest.md
- docs/en_US/rules/sources/http_pull.md
- docs/zh_CN/rules/sinks/rest.md
- docs/zh_CN/rules/sources/http_pull.md
- docs/zh_CN/rules/sources/mqtt.md
- etc/sinks/mqtt.json
- etc/sinks/rest.json
- etc/sources/httppull.json
- internal/server/rest.go
- internal/topo/sink/rest_sink.go
- internal/topo/source/httppull_source.go
> fix(http plugin): add cert/key/ca support for http source/sink

- internal/topo/node/source_node.go
- internal/topo/node/source_pool.go
bring back source dynamic buffer for shared sources
Closes: #1106 
> fix(source): source buffer metric fix and refactors

- .github/workflows/build_packages.yaml
- .github/workflows/run_test_case.yaml
- deploy/docker/Dockerfile
- deploy/docker/Dockerfile-alpine
- deploy/docker/Dockerfile-kubernetes-tool
- deploy/docker/Dockerfile-slim
- extensions.mod
- extensions.sum
- extensions/functions/labelImage/labelImage.go
- extensions/sinks/influx/influx.go
- internal/conf/syslog.go
- internal/conf/syslog_win.go
- internal/topo/connection/client_edgex.go
- internal/topo/connection/client_edgex_test.go
- internal/topo/source/edgex_source.go
- internal/topo/source/edgex_source_test.go
- internal/topo/topotest/warning_test.go
- test/edgex/benchmark/pub.go
- test/edgex/pub.go
- test/edgex/sub/sub.go
alpine and slim image support python
> build: bump golang version to 1.17.3

- internal/topo/sink/log_sink.go
> fix(log): print string result as before

- internal/topo/sink/edgex_sink.go
- internal/topo/sink/edgex_sink_test.go
- internal/topo/source/edgex_source.go
- internal/topo/source/edgex_source_test.go
> feat(edgex): support object type

- internal/topo/planner/analyzer.go
- internal/topo/planner/planner_test.go
> fix(analyzer): fix anonymous field name dup problem

- deploy/docker/README.md
- docs/en_US/extension/portable/python_sdk.md
- docs/zh_CN/extension/portable/python_sdk.md
> doc(portable): docs to mention python image

- internal/meta/yamlConfigMeta.go
- internal/meta/yamlConfigMeta_test.go
- internal/meta/yaml_config_ops.go
- internal/plugin/native/manager.go
- internal/server/rest.go
- internal/server/rest_test.go
- internal/topo/topo.go
> fix(ui): backend support for ui update config key

- deploy/docker/README.md
- docs/en_US/operation/configuration_file.md
- docs/en_US/plugins/plugins_tutorial.md
- docs/zh_CN/plugins/plugins_tutorial.md
> fix(docs): fix typo in docs

- deploy/docker/README.md
> fix(docs): update docker readme arch image

- .github/workflows/run_fvt_tests.yaml
- deploy/chart/kuiper/README.md
- deploy/chart/kuiper/README_zh.md
- deploy/chart/kuiper/values.yaml
- deploy/docker/README.md
- deploy/docker/test/mqtt_source.yaml
- docs/en_US/getting_started.md
- docs/en_US/manager-ui/overview.md
- docs/en_US/quick_start_docker.md
- docs/en_US/rules/sources/mqtt.md
- docs/en_US/sqls/streams.md
- docs/zh_CN/getting_started.md
- docs/zh_CN/manager-ui/overview.md
- docs/zh_CN/quick_start_docker.md
- docs/zh_CN/rules/sources/mqtt.md
- docs/zh_CN/sqls/streams.md
- etc/connections/connection.yaml
- etc/mqtt_source.json
- etc/mqtt_source.yaml
- internal/topo/connection/client_mqtt.go
- internal/topo/connection/client_mqtt_test.go
- internal/topo/connection/connect_selector_test.go
- internal/topo/source/mqtt_source.go
> fix(mqtt): remove mqtt server array

- deploy/chart/kuiper/values.yaml
- docs/en_US/operation/config/configuration_file.md
- docs/en_US/operation/restapi/plugins.md
- docs/en_US/sqls/tables.md
- docs/zh_CN/operation/config/configuration_file.md
- docs/zh_CN/operation/restapi/plugins.md
- docs/zh_CN/sqls/tables.md
- etc/kuiper.yaml
> fix(docs): update docs

- internal/server/rpc.go
- internal/topo/sink/log_sink.go
> fix(cli): fix cli query multiple data showing up in one row

- internal/topo/node/sink_node.go
- internal/topo/node/sink_node_test.go
> fix(node): Fix omitEmpty when sendSingle is set

- .github/dockerfile/Dockerfile.centos
- .github/dockerfile/Dockerfile.debian
- .github/workflows/build_base_image.yaml
- .github/workflows/build_packages.yaml
- .github/workflows/run_fvt_tests.yaml
- .github/workflows/run_test_case.yaml
- deploy/docker/Dockerfile
- deploy/docker/Dockerfile-alpine
- deploy/docker/Dockerfile-kubernetes-tool
- deploy/docker/Dockerfile-slim
- deploy/docker/Dockerfile-slim-python
- extensions.mod
- extensions/go.mod
- go.mod
> revert(go): downgrade go from 1.17 to 1.16

- docs/en_US/operation/manager-ui/overview.md
- docs/zh_CN/operation/manager-ui/overview.md
> docs(manager ui): use relative image path in manager ui

- internal/plugin/portable/runtime/connection.go
- internal/server/rest.go
> fix(portable): fix rule hang problem when python plugin has exited

- internal/topo/node/source_pool.go
The ruleId will be "$$source_pool_{{streamName}}" and the opId will be "source_pool_{{streamName}}". To prevent an error of running portable plugin and any other plugin logic that may depend on a non empty ruleId/opId
Closes #1172
> fix(source): assign ruleId and opId for shared source instance

- internal/processor/stream.go
- internal/server/rest.go
> fix(rest): return error when replace stream sql does not match name

- internal/topo/connection/clients/edgex/edgex_wrapper.go
- internal/topo/connection/clients/mqtt/mqtt_wrapper.go
- internal/topo/connection/clients/type.go
- internal/topo/sink/edgex_sink.go
- internal/topo/sink/mqtt_sink.go
- internal/topo/source/edgex_source.go
- internal/topo/source/mqtt_source.go
- pkg/api/stream.go
> refactor(connection): use map[string]interface{} to hold parameters

- internal/topo/connection/clients/client_registy.go
- internal/topo/connection/clients/mqtt/mqtt.go
> fix(log): replace the plaintext password with *** in log

- deploy/docker/Dockerfile-slim
> fix(plg): fix tdengine crash

- .github/workflows/build_base_image.yaml
> build: update base image go version

- .github/dockerfile/Dockerfile.centos
- .github/dockerfile/Dockerfile.debian
- .github/workflows/build_packages.yaml
- .github/workflows/run_fvt_tests.yaml
- .github/workflows/run_test_case.yaml
- deploy/docker/Dockerfile
- deploy/docker/Dockerfile-alpine
- deploy/docker/Dockerfile-kubernetes-tool
- deploy/docker/Dockerfile-slim
- deploy/docker/Dockerfile-slim-python
- extensions.mod
- extensions/go.mod
- go.mod
> build: back to go 1.17

- internal/topo/source/mqtt_source.go
> fix(mqtt): fix log typo

- docs/en_US/sqls/built-in_functions.md
- docs/zh_CN/sqls/built-in_functions.md
- internal/binder/function/funcs_misc.go
- internal/topo/planner/planner_test.go
- internal/xsql/funcValuer.go
- internal/xsql/funcsAggregate.go
- internal/xsql/functionRuntime.go
- internal/xsql/parser.go
- internal/xsql/parser_test.go
- internal/xsql/valuer.go
- pkg/ast/expr.go
Otherwise, the state may interfere
> fix(parser): assign funcId in parser

- .github/workflows/build_packages.yaml
> fix(sql plugin): set latest tag on slim suffix docker image

- etc/sinks/neuron.json
- etc/sinks/tdengine.json
> fix(neuron): add missing properties in neuron.json

- docs/directory.json
- docs/zh_CN/README.md
> fix(doc): add sql to nav and fix typo

- docs/en_US/CONTRIBUTING.md
- docs/zh_CN/CONTRIBUTING.md
> fix(docs): add debug instructions for edgex code

- internal/topo/operator/project_operator.go
- internal/xsql/collections.go
> fix(valuer): allow window_start() and window_end() as parameter

- .github/workflows/run_fvt_tests.yaml
- build-plugins.sh
- go.mod
- go.sum
- test/plugin_end_2_end.jmx
- test/prepare_plugins.sh
- test/setup_env.sh
- test/start_kuiper.sh
> fix(integration test): add integration test for tdengine/sql

- deploy/docker/Dockerfile
Signed-off-by: Jianxiang Ran <jianxiang.ran@emqx.io>
> fix(docker): make dev docker image has same volumn location format with others

- .github/workflows/deploy_docs.yaml
Signed-off-by: Swilder-M <poxiaobbs@gmail.com>
> ci(docs): docs dist use cos

- docs/en_US/extension/external/external_func.md
- docs/en_US/tutorials/ai/tensorflow_lite_tutorial.md
- docs/zh_CN/extension/external/external_func.md
- docs/zh_CN/tutorials/ai/tensorflow_lite_tutorial.md
> fix(docs): update docs for external service protobuf package format and tensflow function plugin download path

- internal/topo/operator/order_operator.go
- internal/topo/topotest/rule_test.go
- internal/xsql/parser.go
- internal/xsql/parser_test.go
- internal/xsql/valuer.go
- pkg/ast/statement.go
- pkg/ast/visitor.go
> fix(sql): fix sql order by alias bug

- internal/server/meta_plugin_init.go
> fix(plugin): return error message when read native plugin info have error

- internal/topo/operator/filter_test.go
- internal/xsql/parser.go
- internal/xsql/parser_test.go
> fix(sql): support normal expression after IN clause

- internal/meta/sinkMeta.go
- internal/meta/sourceMeta_test.go
> fix(ui): fix default array properties is null

- internal/topo/planner/dataSourcePlan.go
- internal/topo/planner/joinAlignPlan.go
- internal/topo/planner/planner_test.go
- internal/topo/topotest/window_rule_test.go
> fix(planner): filter must not apply on table before join align

- internal/converter/protobuf/converter_test.go
- internal/converter/protobuf/fieldConverterSingleton.go
- internal/schema/registry_test.go
- internal/schema/test/test1.proto
- pkg/cast/cast.go
> fix(proto): fix encode/decode problem for repeated field

- docs/en_US/sqls/lexical_elements.md
- docs/en_US/sqls/query_language_elements.md
- docs/zh_CN/sqls/lexical_elements.md
- docs/zh_CN/sqls/query_language_elements.md
- internal/xsql/lexical.go
- internal/xsql/parser.go
- internal/xsql/parser_test.go
- internal/xsql/valuer.go
- internal/xsql/valuer_test.go
- pkg/ast/expr.go
- pkg/ast/funcArgsValidator.go
- pkg/ast/token.go
> Between and like support

- internal/server/rest.go
- internal/server/rule_manager.go
> fix(rest): Unify rule status response

- internal/processor/rule.go
- internal/server/rest.go
- internal/server/rpc.go
- internal/server/rule_manager.go
> fix(restapi): add name field for get rules response

- docs/en_US/rules/sinks/plugin/sql.md
- docs/en_US/rules/sinks/plugin/tdengine.md
- docs/zh_CN/rules/sinks/plugin/sql.md
- etc/sinks/sql.json
- etc/sinks/tdengine.json
> fix(ui): bugfix for docs

- .github/dockerfile/Dockerfile.centos
- .github/dockerfile/Dockerfile.debian
- .github/workflows/build_base_image.yaml
> fix(ci): upgrade build base image to go 1.18.5

- .github/dockerfile/Dockerfile.debian
> fix(ci): add wget before using

- .github/dockerfile/Dockerfile.debian
> fix(ci): fix arm v7 goland download

- .github/dockerfile/Dockerfile.debian
> fix(ci): add git make tool for base image

- .github/dockerfile/Dockerfile.debian
> fix(ci): add curl procps tool for base image

- .github/dockerfile/Dockerfile.debian
> fix(ci): build upx from source code for base image

- .github/dockerfile/Dockerfile.alpine
- .github/workflows/build_base_image.yaml
> fix(ci): add alpine base build image

- .github/dockerfile/Dockerfile.alpine
- .github/dockerfile/Dockerfile.centos
- .github/dockerfile/Dockerfile.debian
> fix(ci): fix alpine dubious ownership in repo problem

- internal/server/meta_plugin_init.go
> fix(plugin): remove strict check for plugin download

- .github/workflows/build_packages.yaml
- build-plugins.sh
- deploy/docker/Dockerfile
- deploy/docker/Dockerfile-alpine
- deploy/docker/Dockerfile-slim
- deploy/docker/Dockerfile-slim-python
> fix(ci): build plugins with alpine build image

- etc/sinks/edgex.json
- internal/server/rest.go
> fix(ui): remove chunked encoding for rest response

- internal/plugin/native/manager.go
> fix(plugin): cache the symbol when plugin set up

- docs/directory.json
- docs/en_US/rules/sources/builtin/http_push.md
- docs/zh_CN/rules/sources/builtin/http_push.md
- etc/kuiper.yaml
- etc/sources/httppush.json
- etc/sources/httppush.yaml
- internal/binder/io/builtin.go
- internal/conf/conf.go
- internal/conf/conf_test.go
- internal/topo/neuron/source.go
- internal/topo/node/sink_node_test.go
- internal/topo/source/httppush_source.go
- internal/topo/source/httpserver/data_server.go
- internal/topo/source/httpserver/data_server_test.go
- pkg/errorx/errors.go
- Support multiple endpoints
- Use global data server
> httppush source 

- extensions/sinks/influx/influx.go
Signed-off-by: crui <crui@relaper.com>
> fix(plugin): check whether dataTemplate is an empty field

- extensions/sinks/image/image.go
- extensions/sinks/image/image.json
- internal/topo/node/sink_node.go
> fix(plugin): fix sink image plugin config error

- docs/directory.json
- docs/en_US/tutorials/ai/python_tensorflow_lite_tutorial.md
- docs/zh_CN/tutorials/ai/python_tensorflow_lite_tutorial.md
> doc(plugin): tutorial to use python plugin

- internal/xsql/row.go
> fix(sql): should not change message map to avoid concurrent read/write

- etc/sources/redis.json
- etc/sources/redis.yaml
- internal/binder/io/ext_redis.go
- internal/plugin/portable/test/portable_rule_test.go
- internal/topo/redis/lookup.go
- internal/topo/redis/lookup_test.go
- internal/topo/redis/sink.go
> feat(lookup): redis lookup source

- extensions/sources/sql/sqlLookup.go
- internal/topo/memory/lookupsource.go
- internal/topo/memory/lookupsource_test.go
- internal/topo/node/lookup_node.go
- internal/topo/node/lookup_node_test.go
- internal/topo/planner/dataSourcePlan.go
- internal/topo/planner/lookupPlan.go
- internal/topo/planner/planner.go
- internal/topo/planner/planner_test.go
- internal/topo/redis/lookup.go
- internal/topo/redis/lookup_test.go
- pkg/api/stream.go
Fields can help to create a better SQL template
> feat(lookup): add fields parameter to the lookup func

- internal/topo/node/dynamic_channel_buffer.go
- internal/topo/node/dynamic_channel_buffer_test.go
> opt(buffer): Optimize dynamic buffer and add unit test

- internal/plugin/portable/manager.go
- internal/plugin/portable/runtime/plugin_ins_manager.go
> fix(portable): need to close process when deleting plugin

- extensions/sources/sql/sql.yaml
- internal/topo/lookup/cache/cache.go
- internal/topo/lookup/cache/cache_test.go
- internal/topo/lookup/table.go
- internal/topo/node/conf/source.go
- internal/topo/node/lookup_node.go
- internal/topo/node/lookup_node_test.go
- internal/topo/node/source_node.go
- internal/topo/node/source_node_test.go
Add cache support to lookup node
> feat(lookup): lookup cache

- extensions/sinks/sql/sql.go
- extensions/sinks/sql/sql_test.go
1. Support updatable for SQL sink
2. Add unit test
3. Fix a bug for writing []map, generated SQL miss table
> feat(sink): updatable SQL sink

- test/alert_init_data.txt
- test/alert_update_data.txt
- test/collect_data.txt
- test/lookup_table_memory.jmx
- test/lookup_table_result_data.txt
- test/run_jmeter.sh
Cover the testing of updatable sink and lookup table
> test(lookup): memory lookup table fvt

- internal/xsql/row.go
- internal/xsql/row_test.go
> feat(row): let affiliate row become thread safe (#1429)

- .github/workflows/build_packages.yaml
> fix(ci): run build packages in all branches

- docs/en_US/operation/config/configuration_file.md
- docs/zh_CN/operation/config/configuration_file.md
- internal/server/server.go
> feat(server): init ruleset

- docs/en_US/operation/config/configuration_file.md
- docs/zh_CN/operation/config/configuration_file.md
resolves #1445
Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>
> Fix and add example of environment variables

- docs/en_US/rules/sinks/overview.md
- docs/zh_CN/rules/sinks/overview.md
- etc/multilingual/en_US.ini
- etc/multilingual/zh_CN.ini
- extensions/sources/sql/sql.go
- extensions/sources/zmq/zmq.go
- internal/conf/yaml_config_ops.go
- internal/meta/sinkMeta.go
- internal/meta/yamlConfigMeta.go
- internal/server/meta_init.go
- internal/topo/connection/clients/client_registy.go
- internal/topo/connection/clients/edgex/edgex_wrapper.go
- internal/topo/connection/clients/mqtt/mqtt_wrapper.go
- internal/topo/connection/clients/type.go
- internal/topo/context/default.go
- internal/topo/context/func_context.go
- internal/topo/node/conf/sink.go
- internal/topo/node/node.go
- internal/topo/node/sink_node.go
- internal/topo/sink/edgex_sink.go
- internal/topo/sink/mqtt_sink.go
- internal/topo/source/edgex_source.go
- internal/topo/source/httppull_source.go
- internal/topo/source/mqtt_source.go
- pkg/api/stream.go
> fix(fea): support sink config by resource id

- internal/plugin/native/manager.go
- internal/server/server.go
> fix(rule): do not recover rule that has error

- etc/sinks/redis.json
- internal/schema/registry.go
- internal/schema/registry_test.go
- internal/server/server.go
- internal/topo/node/sink_node_test.go
An error happens when upgrading from early docker compose. We need to create new folders inside data folder which will have permission problem because the volume was created by previous kuiper user.
> feat(edgex): support default edgex docker compose permission setting

- internal/topo/operator/analyticfuncs_operator.go
- internal/topo/topotest/rule_test.go
> fix(op): analytic functions dependency

- docs/zh_CN/sqls/windows.md
> fix(doc): typo for window filter

- internal/conf/connect_selector.go
- internal/conf/yaml_config_ops.go
- internal/conf/yaml_config_ops_test.go
- internal/meta/connectionMeta.go
> fix(connection): share connection do not take effect

- internal/processor/ruleset_test.go
- internal/topo/node/watermark.go
- internal/topo/node/window_op.go
- internal/topo/topotest/window_rule_test.go
- internal/xsql/collection.go
- internal/xsql/collection_test.go
> fix(window): time window should always triggered by time

- .github/workflows/build_packages.yaml
> fix(plugin): build labelImage for tensorflow in alpine

- .github/workflows/build_packages.yaml
> fix(plugin): remove labelImage plugin for alpine

- internal/conf/connect_selector.go
- internal/conf/connect_selector_test.go
- internal/topo/node/conf/source.go
- internal/topo/node/conf/source_test.go
> fix(conf): fix config overwritten by environment issue

- internal/binder/function/funcs_agg.go
- internal/binder/function/funcs_agg_test.go
- internal/topo/operator/project_test.go
> fix(func): avg/max/min should support int64 inputs

- internal/xsql/row.go
It is possible to have multiple sinks call ToMap at once
Closes #1493
> fix(row): add lock for ToMap to avoid concurrent map write for 1.7.x

- extensions/sources/sql/sql.json
> fix(meta): update sql source json to add lookup configuration

- extensions/functions/labelImage/labelImage.go
- internal/meta/sinkMeta.go
- internal/meta/sourceMeta.go
- internal/meta/yamlConfigMeta.go
- internal/plugin/native/manager.go
- internal/plugin/portable/manager.go
> fix(meta): remove meta data when plugin deleted

- internal/processor/rule_test.go
- internal/server/rest.go
- internal/server/rpc.go
- internal/server/rule_manager.go
Allow to not starting rule when creating
> fix(rule): obey triggered value when creating rules

- internal/processor/rule.go
- internal/processor/rule_test.go
- internal/server/rest.go
- internal/server/rpc.go
- pkg/api/stream.go
> fix(rule): obey triggered status when creating rule

- internal/binder/meta/bind.go
- internal/meta/connectionMeta_test.go
- internal/meta/sourceMeta.go
- internal/meta/sourceMeta_test.go
- internal/plugin/native/manager.go
- internal/plugin/portable/manager.go
- internal/server/meta_init.go
Distinguish between scan source and lookup source
> feat(meta): metadata/sources add kind parameter

- etc/mqtt_source.json
- etc/sources/file.json
- etc/sources/httppull.json
- etc/sources/httppush.json
- etc/sources/memory.json
- etc/sources/redis.json
- extensions/sources/sql/sql.json
- extensions/sources/zmq/zmq.json
- internal/binder/meta/bind.go
- internal/meta/connectionMeta_test.go
- internal/meta/sourceMeta.go
- internal/meta/sourceMeta_test.go
- internal/plugin/native/manager.go
- internal/plugin/portable/manager.go
- internal/server/meta_init.go
> feat(meta): update metadata/source api 

- internal/topo/planner/analyzer.go
- internal/topo/planner/planner_test.go
> fix(func): analytic depending on alias must run alias firstly

- internal/topo/rule/ruleState.go
- test/change_rule_status.jmx
regardless of the current state
> fix(rule): rule start/stop should always send signal

- .github/workflows/build_packages.yaml
- Makefile
- docs/directory.json
- docs/en_US/rules/sources/plugin/video.md
- docs/zh_CN/rules/sources/plugin/video.md
- extensions/sources/video/install.sh
- extensions/sources/video/video.go
- extensions/sources/video/video.json
- extensions/sources/video/video.yaml
> refactor(plugin): rename rtsp source to video source

- .github/workflows/build_packages.yaml
- extensions/functions/tfLite/tflite.conf
- extensions/sources/video/install.sh
Signed-off-by: Jianxiang Ran <jianxiang.ran@emqx.io>
> fix(plugin): fix video and tflite build error

- extensions/sources/video/install.sh
Signed-off-by: Jianxiang Ran <jianxiang.ran@emqx.io>
> fix(plugin): fix error in video source install script

- internal/topo/rule/ruleState.go
if the plugin was deleted previously
> fix(rule): rule hang while restarting

- internal/processor/stream.go
- internal/processor/stream_test.go
- internal/schema/registry.go
- internal/server/rest.go
> feat(schema): API to get the inferred schema

- etc/sources/file.yaml
- internal/topo/node/source_node.go
- internal/topo/operator/preprocessor_test.go
- internal/topo/source/file_source.go
- internal/topo/source/file_source_test.go
- internal/topo/source/test/csv/a.csv
- internal/topo/source/test/csv/b.csv
- internal/topo/source/test/json/f1.json
- internal/topo/source/test/json/f2.json
- internal/topo/source/test/json/f3.json
- internal/topo/source/test/test.json
- internal/topo/topotest/mock_topo.go
1. Add a lot of new properties
2. Add new format csv
3. Allow to use in stream
4. Monitor both folder and file
Closes #1556
> feat(file): refactor file source

- .github/workflows/build_base_image.yaml
- .github/workflows/build_packages.yaml
Signed-off-by: Rory Z <rory-z@outlook.com>
> chore(ci): update some github action version

- extensions/sinks/tdengine/tdengine.go
- extensions/sinks/tdengine/tdengine_test.go
> fix(plugin): can not use timestamp from message as tdengine timestamp index

- docs/directory.json
- docs/en_US/api/cli/configuration.md
- docs/en_US/api/restapi/configuration.md
- docs/zh_CN/operation/cli/configuration.md
- docs/zh_CN/operation/restapi/configuration.md
> fix(doc): add full data export/import docs

- etc/ops/switch.json
- internal/topo/graph/io.go
- internal/topo/graph/node.go
- internal/topo/node/switch_node.go
- internal/topo/node/switch_node_test.go
- internal/topo/planner/planner_graph.go
- internal/topo/topo.go
- internal/topo/topotest/rule_test.go
- internal/topo/topotest/window_rule_test.go
- pkg/api/stream.go
> feat(graph): add switch node

- go.mod
- go.sum
- internal/binder/function/funcs_agg.go
- internal/binder/function/funcs_agg_test.go
> fea(function): add stats function for built-in function

- internal/server/rest.go
> fix(config): recover all rules when import data

- build-plugins.sh
- extensions/functions/accumulateWordCount/accumulateWordCount.json
- extensions/functions/countPlusOne/countPlusOne.json
- extensions/functions/echo/echo.json
- extensions/functions/labelImage/labelImage.json
- extensions/functions/tfLite/tfLite.json
> fix(meta): fix typo in meta json description

- internal/plugin/native/manager.go
- internal/plugin/portable/manager.go
- internal/schema/registry.go
> fix(config): schema data config import export support

- docs/en_US/operation/manager-ui/overview.md
- docs/en_US/sqls/custom_functions.md
- docs/zh_CN/operation/manager-ui/overview.md
- docs/zh_CN/sqls/custom_functions.md
> fix(docs): add ekuiper endpointurl to ekuiper manager by env

- docs/en_US/sqls/built-in_functions.md
- docs/zh_CN/sqls/built-in_functions.md
> fix(docs): add tutorial for when function

- internal/plugin/portable/factory.go
- internal/plugin/portable/manager.go
- internal/plugin/portable/runtime/plugin_ins_manager.go
- internal/processor/ruleset.go
When deleting plugins, remove the func instance cache
> fix(portable): adapt to import data

- docs/en_US/guide/rules/graph_rule.md
- docs/zh_CN/guide/rules/graph_rule.md
> doc: add more description for switch node

- internal/server/rest_test.go
- internal/server/rule_manager.go
> fix(ut): add more ut for rule stream restapi

- docs/en_US/extension/portable/overview.md
- docs/en_US/extension/portable/python_sdk.md
- docs/zh_CN/extension/portable/overview.md
- docs/zh_CN/extension/portable/python_sdk.md
- internal/plugin/portable/runtime/connection.go
- internal/plugin/portable/runtime/plugin_ins_manager.go
> feat(portable): support conda env for python plugin

- etc/sources/httppull.json
- etc/sources/httppull.yaml
- internal/topo/mock/test_source.go
- internal/topo/node/source_node_test.go
- internal/topo/source/httppull_source.go
- internal/topo/source/httppull_source_test.go
- pkg/cast/cast.go
> feat(source): support oAuth for httppull

- internal/binder/io/builtin.go
- internal/io/http/client.go
- internal/io/http/client_test.go
- internal/io/http/httppull_source.go
- internal/io/http/httppull_source_test.go
- internal/io/http/httppush_source.go
- internal/io/http/rest_sink.go
Also refactor to use the same codebase of http client across source and sink
> feat(sink): enable oAuth for rest sink

- internal/binder/function/funcs_math.go
- internal/binder/function/funcs_math_test.go
1. Bitand, bitor, bitxor argument error
2. Math function return nil for NaN result to comply with SQL standard
3. Add ut
Closes #1708
> fix(funcs): fix math func errors

- internal/topo/topotest/window_rule_test.go
- internal/xsql/row.go
> fix(tuple): group tuple content must clone before pick

- .github/dockerfile/Dockerfile.alpine
- .github/dockerfile/Dockerfile.debian
- .github/workflows/build_packages.yaml
- .github/workflows/run_fvt_tests.yaml
- deploy/docker/Dockerfile
- deploy/docker/Dockerfile-slim
- deploy/docker/Dockerfile-slim-python
> feat: remove zmq from EdgeX source

- extensions/functions/labelImage/labelImage.json
- extensions/functions/tfLite/tfLite.json
> fix(meta): add missing field for plugin json, or labels can not show in ui

- docs/en_US/edgex/edgex_rule_engine_command.md
- docs/zh_CN/edgex/edgex_rule_engine_command.md
edgex's command service can also receive commands via the external messagebus.
> fix (doc): update edgex command messaging tutorial doc 

- extensions/sinks/sql/sql.go
- extensions/sources/sql/sql.go
- extensions/sources/sql/sqlLookup.go
- extensions/sqldatabase/sqlgen/sqlgen.go
- extensions/util/pool.go
> feat(plugin): support sink/source for dm database

- internal/io/file/file_sink.go
- internal/io/file/file_sink_test.go
- internal/io/file/file_writer.go
- internal/io/file/writer_hooks.go
> fix(sink): fix file sink line seperator problems

- deploy/docker/Dockerfile-slim
> fix(docker): use debian:buster-slim for slim docker image

- extensions/sources/video/video.go
- extensions/sources/zmq/zmq.go
- internal/io/file/file_source.go
- internal/io/file/file_source_test.go
- internal/io/file/test/test.lines
- internal/io/http/client.go
- internal/io/http/httppull_source.go
- internal/io/http/httppull_source_test.go
> feat: support more source for json list object

- internal/binder/mock/mock_factory.go
- internal/converter/binary/converter.go
- internal/converter/binary/converter_test.go
- internal/converter/json/converter.go
- internal/converter/json/converter_test.go
- internal/io/sink/log_sink.go
- internal/io/sink/nop_sink.go
- internal/pkg/filex/parser.go
- internal/topo/collector/func.go
- internal/topo/graph/io.go
- pkg/api/stream.go
- pkg/kv/kv.go
- test/plugins/pub/zmq_pub.go
This is a preprocessed PR for introducing golangci-lint.
> style: align with gofumpt format style

- internal/server/server.go
This is a complementary PR to lf-edge/ekuiper#1847.
> fix: use print-style functions

- internal/topo/transform/template.go
This is a complementary PR to lf-edge/ekuiper#1849.
> refactor: fix unreachable codes

- internal/converter/protobuf/fieldConverterSingleton.go
- internal/pkg/httpx/http.go
- internal/server/middleware/auth_test.go
- internal/server/os.go
- internal/server/plugin_init.go
- internal/server/rest_test.go
- internal/topo/planner/planner_graph.go
- internal/topo/transform/func.go
- internal/xsql/row_test.go
- pkg/cast/cast.go
- test/edgex/pub.go
> refactor: remove unnecessary conversion

- docs/en_US/guide/rules/graph_rule.md
- docs/zh_CN/guide/rules/graph_rule.md
- internal/topo/graph/io.go
- internal/topo/planner/planner_graph.go
- internal/topo/planner/planner_graph_test.go
- test/graph_lookup_rule.jmx
> feat(graph): support join lookup table

- internal/topo/planner/planner_graph.go
- internal/topo/planner/planner_graph_test.go
Make it easier to identify topo problems
> feat(graph): update the parse error messages

- internal/io/edgex/edgex_source.go
Closes https://github.com/lf-edge/ekuiper/issues/1755
> fix: exception metric is wrong

- internal/topo/node/watermark.go
- internal/topo/node/window_op.go
- internal/topo/topotest/mocknode/mock_data.go
- internal/topo/topotest/window_rule_test.go
> fix(window): fix wrong first start time

- internal/conf/time.go
- internal/io/file/file_sink.go
- internal/io/sink/send_manager.go
- internal/topo/checkpoint/coordinator.go
- internal/topo/lookup/cache/cache.go
- internal/topo/node/watermark.go
- internal/topo/node/window_op.go
- internal/topo/node/window_op_test.go
- internal/topo/planner/planner.go
- internal/topo/planner/planner_graph.go
- internal/topo/planner/planner_test.go
- internal/topo/planner/windowPlan.go
- internal/topo/rule/ruleState.go
- internal/xsql/parser.go
- internal/xsql/parser_test.go
- pkg/ast/statement.go
Window length of 2 minutes will now align to second 0. Which is different with window length of 120 seconds.
> fix(window): align time based on unit

- internal/topo/operator/order_test.go
- internal/xsql/sorter.go
> fix: fix sort interface

- internal/io/http/client.go
- internal/io/http/httppull_source.go
This PR will check oAuth token expiration on every HTTP pulling and refresh token if expired.
> feat(httppull): refresh token on pulling

- docs/en_US/sqls/functions/transform_functions.md
- docs/zh_CN/sqls/functions/transform_functions.md
- internal/binder/function/funcs_misc.go
- internal/binder/function/funcs_misc_test.go
feat(function): add hex/int conversion functions
> feat(function): add hex/int conversion functions

- docs/zh_CN/configuration/global_configurations.md
> docs: duplicate ignoreCase annotation

- .github/workflows/build_packages.yaml
- Makefile
> fix(release): disable upx for non-linux platforms

- docs/en_US/sqls/functions/transform_functions.md
- docs/zh_CN/sqls/functions/transform_functions.md
- internal/binder/function/funcs_misc.go
- internal/binder/function/funcs_misc_test.go
> feat: add `convert_tz` for timezone conversion

- docs/en_US/guide/sources/builtin/http_pull.md
- docs/zh_CN/guide/sources/builtin/http_pull.md
- internal/conf/time.go
- internal/io/http/client.go
- internal/io/http/httppull_source.go
- internal/io/http/httppull_source_test.go
- internal/io/mock/test_source.go
- internal/io/mqtt/mqtt_source.go
- internal/io/receiver.go
Allow user to specify dynamic time range by url or body.
> feat(source): httppull supports time range

- cmd/kuiper/main.go
- cmd/kuiperd/main.go
- docs/en_US/configuration/configuration.md
- docs/zh_CN/configuration/configuration.md
- internal/conf/path.go
- internal/conf/path_test.go
- internal/server/server.go
> feat: export config path

- deploy/docker/README.md
> fix(doc): update dockerfile link

- docs/en_US/guide/sinks/builtin/redis.md
- docs/en_US/guide/sinks/plugin/influx.md
- docs/en_US/guide/sinks/plugin/influx2.md
- docs/en_US/guide/sinks/plugin/kafka.md
- docs/zh_CN/guide/sinks/builtin/redis.md
- docs/zh_CN/guide/sinks/plugin/influx.md
- docs/zh_CN/guide/sinks/plugin/influx2.md
- docs/zh_CN/guide/sinks/plugin/kafka.md
- Remove redundant space from SQLs
- Improve Kafka docs to use <YOUR_HOST_IP> placeholder
cc: @ngjaying Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️
> docs: Remove redundant space

- docs/en_US/guide/sinks/overview.md
- docs/zh_CN/guide/sinks/overview.md
- internal/conf/conf.go
- internal/conf/conf_test.go
- internal/topo/node/cache/sync_cache.go
- internal/topo/node/sink_node.go
- internal/topo/node/sink_node_test.go
- Support resend priority
- Support resend field update
- Docs
- Ut
> feat(sink): resend strategy

- internal/topo/node/cache/sync_cache.go
- internal/topo/node/sink_node.go
- internal/topo/node/sink_node_test.go
Refactor the sink node flow to accommodate both batch and cache
> feat(sink): support batch + resend

- internal/topo/planner/planner_graph.go
- internal/topo/planner/planner_graph_test.go
fix bug :schemaName and schemaMessage not set
> fix(graph): set schema id by name/message

- internal/binder/function/funcs_misc.go
- internal/binder/function/funcs_misc_test.go
- internal/xsql/funcs_validator_test.go
- pkg/cast/cast.go
- pkg/cast/cast_test.go
> feat: add bytea to CAST function

- internal/conf/conf.go
- internal/conf/log_test.go
This PR is an enhancement for #2138.
> feat: extend `gcOutdatedLog` for all log files

- docs/en_US/guide/sinks/builtin/file.md
- docs/zh_CN/guide/sinks/builtin/file.md
- internal/io/file/file_sink.go
- internal/io/file/file_sink_test.go
Fix checkInterval validation and doc
> fix(file): checkInterval validation

- internal/plugin/native/manager.go
- internal/plugin/portable/manager.go
- internal/plugin/portable/runtime/plugin_ins_manager.go
- internal/plugin/wasm/manager.go
Set the default working dir for:
- plugin runtime
- plugin install script
> fix(plugin): set working dir

- internal/xsql/parser.go
- internal/xsql/parser_stream_test.go
> chore: update create stream/table error message

- internal/binder/function/funcs_array.go
- internal/binder/function/funcs_array_test.go
The argument itself should be an array
> fix(func): array_sort works for arr

- internal/binder/function/funcs_obj_test.go
> fix(test): fix obj test random error

- internal/binder/function/funcs_analytic_test.go
- internal/xsql/valuer.go
Nil value should not trigger an error
> fix(func): analytic func nil cache

- docs/directory.json
Signed-off-by: Lena Pan
hilena.pan@gmail.com
> docs: remove duplicate rule chapter

- internal/server/rest_test.go
- internal/server/rule_manager.go
- internal/topo/rule/ruleState.go
- internal/topo/rule/ruleState_test.go
fix: https://github.com/lf-edge/ekuiper/issues/2233
> fix: fix updateTopo ignore triggered

- internal/binder/function/funcs_misc.go
- internal/binder/function/funcs_misc_test.go
- internal/binder/function/funcs_obj.go
- internal/binder/function/funcs_obj_test.go
Refactor to move the function
Do not return nil if encountering nil
> fix(func): object_construct only ignore nil

- internal/topo/node/join_align_node.go
- internal/topo/node/lookup_node.go
- internal/topo/node/switch_node.go
- internal/topo/node/watermark_op.go
- internal/topo/node/window_op.go
Otherwise, node common functions may have error to access stats
> fix(node): should add statManagers

- internal/topo/connection/clients/mqtt/mqtt.go
1. Refactor token handle
2. Add 5 second time out
> fix(mqtt): add publish/sub timeout

- cmd/kuiper/main.go
Adds ability to create plugins using something like `./kuiper create plugin sink influx -zf ./influx.zip`
Closes: https://github.com/lf-edge/ekuiper/issues/1765
The approach I took was to add an additional flag "-zf" or "zipfile".
if passed it will take the path to the file and wrap it in the expected json and then run the function normally if it was passed as a json file.
> feat: create plugin using local file

- extensions/sinks/kafka/ext/kafka.go
Network error should be io error
> fix(sink): kafka sink network io error

- extensions/sinks/sql/ext/sql.go
SQL dataField must handle internally to avoid erasing action field.
> fix(sink): sql datafield handling

- extensions/sinks/kafka/ext/kafka.go
https://github.com/segmentio/kafka-go/blob/f2d9e087266352d276b3cb951b4c668c114b8b75/produce.go#L164-L170
> chore: make kafka client error as io error

- internal/topo/node/window_op.go
> feat(window): ajust to time shift

- CONTRIBUTING.md
This PR adds a Table of Contents to the CONTRIBUTING.md, making it easier for users and contributors to navigate through the document and find specific sections quickly. The Table of Contents includes links to various sections of the contributing guidelines, providing a clear overview of the available content. This enhancement improves the overall accessibility and usability of the CONTRIBUTING.md, enhancing the experience for all users.
> chore: Added table of contents to CONTRIBUTING.md

- app/main.go
This pull request enhances the error handling and user messaging in the codebase. The following improvements have been made:
- **Enhanced Error Handling:** I've introduced more robust error handling to provide detailed error messages when issues occur, making it easier to identify and troubleshoot problems.
- **Informative User Messages:** The code now provides informative messages to the user, improving the overall user experience. Users will receive clear and helpful messages to guide them through the application's processes.
- **Code Readability:** While the primary focus of this pull request is on error handling and user messages, I've also maintained good code formatting and readability.
These improvements aim to make the application more user-friendly and maintainable. Feel free to …
> chore: Improved Error Handling and User Messages

- internal/topo/planner/lookupPlan.go
- internal/topo/planner/planner_test.go
Lookup plan should not push down lookup table related predicate
> fix(planner): lookup plan predicate pushdown

- internal/server/rule_manager.go
> feat: support validate rule graph

- docs/en_US/guide/sinks/plugin/kafka.md
- docs/zh_CN/guide/sinks/plugin/kafka.md
- extensions/sinks/kafka/ext/kafka.go
- extensions/sinks/kafka/kafka.json
1. fix kafka doc default value
2. revise kafka client sending message
3. support ping kafka client
> feat: Kafka sink send out array in batch

- internal/io/http/httpserver/data_server.go
- internal/plugin/native/manager.go
- internal/plugin/native/manager_test.go
1. revise websocket log
2. revise install plugin log
> feat: revise log

- docs/en_US/guide/sinks/plugin/influx2.md
- docs/zh_CN/guide/sinks/plugin/influx2.md
- extensions/sinks/influx2/ext/influx2.go
- extensions/sinks/influx2/ext/influx2_test.go
- extensions/sinks/influx2/ext/line.go
- extensions/sinks/influx2/ext/point.go
- extensions/sinks/influx2/influx2.json
- internal/io/http/client_test.go
- internal/io/http/httppull_source_test.go
- internal/pkg/cert/cert.go
- internal/topo/context/default.go
- internal/topo/node/sink_node.go
- internal/topo/transform/template.go
- Add dynamic TS field
- Support tags template
- Support TLS
- Refactors
> feat: influx v2 sink enhancements

- internal/topo/node/sink_node.go
> fix(sink): influx sink transform setting

- docs/en_US/api/restapi/configKey.md
- docs/en_US/api/restapi/rules.md
- docs/en_US/operation/usage/monitor_with_prometheus.md
- docs/zh_CN/api/cli/streams.md
- docs/zh_CN/api/restapi/configKey.md
- docs/zh_CN/api/restapi/rules.md
- docs/zh_CN/operation/usage/monitor_with_prometheus.md
add following document:
1. Add doc for hidden configKey in meta api.
2. Add doc for explain rule api
3. Add doc for more rule status
4. Add doc for grafana pannel
5. Add doc for cli -json flag
> docs: add document

- app/main.go
Resolving compatibility issues with file systems across different Android systems.
> fix: fix compatibility issues with fs

- etc/sources/simulator.json
- extensions/sinks/influx/influx.json
- extensions/sinks/influx2/influx2.json
- extensions/sinks/sql/sql.json
- extensions/sources/sql/sql.json
> chore: update the json files 

- internal/io/websocket/websocket_sink.go
- internal/trial/manager_test.go
- internal/trial/run.go
1. Static error like sink template syntax errors
2. Runtime error like transform errors
> refactor(trial): catch sink errors

- .github/workflows/run_fvt_tests.yaml
- .github/workflows/run_test_case.yaml
- docs/en_US/guide/ai/python_tensorflow_lite_tutorial.md
- docs/zh_CN/guide/ai/python_tensorflow_lite_tutorial.md
- sdk/python/setup.py
Need to add this since pynng 0.7.4 version.
> chore: add sniffio dependency for python plugins

- docs/en_US/sqls/functions/mathematical_functions.md
- docs/zh_CN/sqls/functions/mathematical_functions.md
- internal/binder/function/funcs_math.go
- internal/binder/function/funcs_math_test.go
> feat: implement CONV function

- internal/topo/context/decoder.go
Avoid constructing error when no error happens
> fix(decode): perf update

- internal/server/rest.go
- internal/server/rest_test.go
- internal/server/rpc.go
- internal/server/rule_manager.go
> fix(rest): return 404 when rule not found

- sdk/python/setup.py
The current version does not work in arm64, so fix version temporarily
> chore: use fixed pynng version

- etc/sinks/redisPub.json
- etc/sources/redisSub.json
- etc/sources/redisSub.yaml
> fix: delete default username of redisPubSub

- internal/server/rpc_test.go
- internal/topo/node/join_align_node.go
- internal/topo/node/lookup_node.go
- internal/topo/node/metric/stats_manager.go
- internal/topo/node/node.go
- internal/topo/node/operations.go
- internal/topo/node/sink_node.go
- internal/topo/node/sink_node_test.go
- internal/topo/node/source_node.go
- internal/topo/node/switch_node.go
- internal/topo/node/watermark_op.go
- internal/topo/node/window_op.go
- internal/topo/topo.go
- pkg/api/stream.go
1. concurrency param becomes useless, will add it back later with in-node concurrency
2. metrics now becomes only 1, remove mutex
> refactor: remove node concurrency

- internal/topo/checkpoint/defs.go
- internal/topo/node/event_window_trigger.go
- internal/topo/node/join_align_node.go
- internal/topo/node/lookup_node.go
- internal/topo/node/metric/stats_manager.go
- internal/topo/node/metric/stats_mem.go
- internal/topo/node/node.go
- internal/topo/node/operations.go
- internal/topo/node/sink_node.go
- internal/topo/node/source_node.go
- internal/topo/node/source_pool.go
- internal/topo/node/switch_node.go
- internal/topo/node/watermark_op.go
- internal/topo/node/window_op.go
do not return error for
1. broadcast
2. new statManager
> refactor: basic function always success

- internal/binder/io/ext_mock.go
- internal/converter/ext_mock.go
- internal/converter/ext_mock_test.go
- internal/topo/node/concurrent.go
- internal/topo/node/decode_op.go
- internal/topo/node/decode_op_test.go
- internal/topo/node/node.go
- internal/topo/planner/planner.go
> feat(node): ordered concurrency support

- internal/topo/rule/ruleState.go
- internal/topo/topo.go
1. When create or recover
2. When update
> fix(topo): avoid plan twice

- docs/en_US/api/cli/services.md
- docs/en_US/api/restapi/services.md
- docs/zh_CN/api/cli/services.md
- docs/zh_CN/api/restapi/services.md
- internal/service/manager.go
- internal/service/manager_test.go
- internal/service/model.go
> feat(service): desc func return addr

- docs/en_US/guide/ai/python_tensorflow_lite_tutorial.md
> fix(docs): clean up en content

- internal/topo/planner/analyzer.go
- internal/topo/planner/planner_test.go
Fix the dependency of non-field funcs, correct the order
> fix(analyzer): correct embedded analytic funcs

- docs/zh_CN/guide/sources/builtin/mqtt.md
> fix: fix zh doc

- internal/io/http/rest_sink.go
- internal/io/http/rest_sink_test.go
> fix(rest): sink should return unrecoverable error

- docs/en_US/sqls/functions/string_functions.md
- docs/zh_CN/sqls/functions/string_functions.md
> docs(func): remind of mem usage for lpad/rpad

- internal/io/mqtt/connection.go
- internal/io/mqtt/mqtt_source_connector.go
- internal/io/mqtt/mqtt_source_connector_test.go
- internal/topo/operator/join_operator.go
MQTT unsubscribe is mandatory, otherwise the handlers are not gc-ed even the connection is closed
> fix: revise mqtt source on msg behavior

- docs/zh_CN/guide/sinks/plugin/tdengine.md
> fix: doc problem for tdengine sink

- internal/plugin/js/export_test.go
- internal/plugin/js/exporter.go
- internal/plugin/native/manager.go
- internal/plugin/portable/manager.go
- internal/schema/registry.go
- internal/server/import_export.go
- internal/server/plugin_init.go
- internal/server/portable_init.go
- internal/server/rpc.go
- internal/server/schema_init.go
- internal/server/service_init.go
- internal/service/manager.go
- internal/service/manager_test.go
introduce ctx for data import api in order to support cancel in async api in future.
> feat: introduce ctx for data import api

- internal/topo/node/source_pool.go
- internal/topo/node/source_pool_test.go
Add reference count. Only cancel when count is 0
> fix(pool): fix source pool cancel

- internal/binder/function/funcs_obj.go
- internal/binder/function/funcs_obj_test.go
- Support nested pick a.b
- Support multiple string args
> feat(function): object pick enhancement (#232)

- contract/api/model.go
- contract/api/sink.go
- contract/api/source.go
- internal/io/memory/memory_test.go
- internal/io/memory/sink.go
- internal/topo/lookup/cache/cache.go
- internal/topo/lookup/cache/cache_test.go
- internal/topo/node/encode_op.go
- internal/topo/node/encode_op_test.go
- internal/topo/node/encrypt_op.go
- internal/topo/node/encrypt_op_test.go
- internal/topo/node/lookup_node.go
- internal/topo/node/sink_node.go
- internal/topo/node/transform_op.go
- internal/topo/node/transform_op_test.go
- internal/topo/planner/planner_sink.go
- internal/topo/planner/planner_sink_test.go
- internal/xsql/collection.go
- internal/xsql/row.go
- pkg/mock/test_sink.go
- Do all dynamic properties calculation in transform op
- Planner identify all dynamic properties for transform op
- Refactor for data models to support props
> feat(sink): add sink dynamic properties support

- internal/topo/operator/windowfunc_operator.go
- internal/topo/operator/windowfunc_operator_test.go
- internal/topo/planner/planner.go
- internal/xsql/parser.go
- pkg/ast/expr.go
- pkg/ast/visitor.go
support partition by and order by clause
> feat: support window function clause

- internal/io/memory/pubsub/manager.go
- internal/io/memory/pubsub/manager_test.go
When restarting rules, the detach may happen after attach. Which makes attach fails because previous attach is still there.
> fix(memory): fix random channel attach problem

- internal/topo/rule/ruleState.go
rs.run should wait setting topo first
> fix: fix NewRuleState

- internal/topo/node/decode_op_test.go
- internal/topo/node/rate_limit.go
- internal/topo/node/rate_limit_test.go
- internal/topo/node/source_node.go
- internal/topo/node/transform_op_test.go
- internal/topo/planner/planner_source.go
- internal/topo/planner/planner_source_test.go
- pkg/message/artifacts.go
- pkg/message/mock.go
> feat(op): support rate limit

- internal/binder/io/builtin.go
- internal/io/mqtt/client/client.go
- internal/io/mqtt/source_test.go
- pkg/modules/connection.go
- refactor connection register
- unify connection register in binder
> fix: register connections before startup

- internal/topo/node/decode_op.go
- internal/topo/node/decode_op_test.go
> fix(op): payload batch decode validate

- internal/topo/node/lookup_node.go
> fix(lookup): update schema

- deploy/docker/Dockerfile
> chore: update docker alpine version

- internal/topo/node/lookup_node.go
- internal/topo/node/lookup_node_test.go
> fix(lookup): no return for empty result

- internal/converter/delimited/converter.go
- pkg/cast/cast.go
- pkg/cast/cast_test.go
cast is a little faster than sprintf
> refactor(csv): use cast to convert string

- deploy/docker/Dockerfile
- deploy/docker/Dockerfile-kubernetes-tool
- go.mod
- go.sum
> chore: update dep versions

- internal/pkg/store/sql/sqlKv.go
- internal/pkg/store/sql/sqlTs.go
Here is a vulnerability which is fixed in the master branch (https://github.com/lf-edge/ekuiper/commit/1a9c745649438feaac357d282959687012b65503) but is not fixed in the branch of master-1.13, maybe it should be backported?
> fix(sql): backport CVE-2024-43406

- internal/server/connection.go
- internal/server/connection_test.go
Return content type application/json
> fix: fix connection api content type header

- docs/en_US/api/restapi/connection.md
- docs/zh_CN/api/restapi/connection.md
- internal/server/connection.go
- internal/server/connection_test.go
- internal/server/rest.go
- pkg/connection/conn.go
- pkg/connection/pool.go
- pkg/connection/pool_test.go
- Let meta save status in status change handler
- Update retry backoff
- Remove unused API
> refactor(conn): save connection status in meta

- internal/plugin/portable/manager.go
- internal/plugin/portable/manager_test.go
Clean plugin from list if run error when installing
> fix(portable): install error cleanup

- internal/io/mqtt/client/client.go
- pkg/nng/sock.go
OnConnect may run before connection handler set
> fix(conn): trigger status handler when init

- internal/io/mqtt/client/client.go
- internal/topo/node/metric/prometheus.go
- internal/topo/node/metric/stats_manager.go
- internal/topo/node/metric/stats_prom.go
- internal/topo/node/source_node.go
> feat(prom): support connection status

- internal/topo/planner/planner_source.go
Fix the problem tha Video source was not decoded now.
> fix(planner): decode for pull byte source

- Makefile
Closes #3362
Fix GOBIN setting error.
> build: fix make lint error

- internal/io/file/line_reader.go
> fix: larger scanner buffer

- extensions/impl/kafka/sink.go
- extensions/impl/kafka/sink_test.go
> fix(kafka): fix dynamic prop problem

- internal/topo/node/window_op.go
> fix(window): sliding delay time

- internal/topo/node/batch_op.go
- internal/topo/planner/planner_sink.go
- internal/topo/planner/planner_sink_test.go
> feat(sink): move batch after encode

- .github/workflows/build_base_image.yaml
- .github/workflows/build_packages.yaml
Skip the latest image bug with ubuntu latest
> chore: specify qemu image

- internal/server/rule_manager.go
- internal/topo/rule/state.go
need to recreate topo in start
> fix(rule): start recover rule start no data

- .github/workflows/build_packages.yaml
> chore(ci): use ubuntu 22-04

- deploy/docker/Dockerfile-slim-python
To avoid libcffi install segment fault
> chore(build): update python base image

- internal/io/neuron/sink_test.go
- internal/io/neuron/source.go
- internal/io/neuron/source_test.go
- pkg/nng/sock.go
- pkg/nng/sock_test.go
Make sure source/sink only functions after connected
> refactor(nng): sync dial

- internal/io/http/rest_sink.go
When set multiple headers, random header will not set
> fix(rest): missing header problem

- internal/io/edgex/sink.go
- internal/io/edgex/sink_test.go
> fix(edgex): slice type convert issues

- extensions/sources/kafka/kafka.json
- extensions/sources/kafka/kafka_test.go
Signed-off-by: diaobisong <bitdbsd11@163.com>
> fix(kafka): fix kafka source bug

- internal/topo/planner/planner.go
- internal/topo/planner/planner_test.go
Rule option disableBufferFullDiscard is not allowed when source is shared
> feat(planner): rule option check

- internal/conf/env_manager.go
- internal/conf/env_manager_test.go
> fix(conf): load connection env wrong type

- internal/server/rpc.go
- internal/server/rule_manager.go
- internal/server/rule_manager_test.go
- internal/topo/rule/state.go
- internal/topo/rule/state_test.go
Add a mechnism for rule state to update trigger when needed.
> feat(rule): eof rule trigger turn to false

- docs/zh_CN/sqls/functions/other_functions.md
- internal/binder/function/funcs_misc.go
- internal/binder/function/funcs_misc_test.go
> fix: fix get_keyed_state

- .github/dockerfile/Dockerfile.debian
To avoid glibc version problem
> fix(ci): base image revert to bullseye

- internal/topo/node/window_inc_agg_op.go
The old way cost too much performance
> fix: improve incremnetal tumbling window perf

- internal/binder/function/funcs_misc.go
Avoid checkpoint save error
Closes #3712
> fix(topo): register lag state type

- internal/converter/schema/schema.go
Avoid rate limit schema not apply problem
> fix(schema): remove wildcard when having schema

- internal/topo/planner/planner_source.go
- internal/topo/planner/planner_source_test.go
- test/edgex_share_connection_sink_rule.jmx
> fix(planner): donot share conn src

- .github/workflows/build_packages.yaml
- contract/go.mod
- deploy/docker/Dockerfile
- deploy/docker/Dockerfile-alpine-python
- deploy/docker/Dockerfile-dev
- deploy/docker/Dockerfile-full
- deploy/docker/Dockerfile-kubernetes-tool
- deploy/docker/Dockerfile-slim
- deploy/docker/Dockerfile-slim-python
- docs/en_US/extension/native/develop/plugins_tutorial.md
- docs/en_US/guide/serialization/serialization.md
- docs/en_US/guide/sinks/plugin/kafka.md
- docs/zh_CN/extension/native/develop/plugins_tutorial.md
- docs/zh_CN/guide/serialization/serialization.md
- docs/zh_CN/guide/sinks/plugin/kafka.md
- go.mod
- go.sum
- go.work
- sdk/go/go.mod
- sdk/go/go.work
- tools/kubernetes/go.mod
> chore: update go and dep version

- fvt/conn_test.go
- internal/topo/planner/planner_source.go
- internal/topo/planner/planner_source_test.go
Only share conn if it must, like neuron stream
> fix(planner): strict share conn

- internal/io/edgex/client/edgex.go
- internal/io/edgex/source.go
Also fix NPE when connect failed
> fix(edgex): tags field access

- fvt/conn_test.go
- internal/io/mqtt/source.go
- internal/topo/planner/planner_source_test.go
Because mqtt connection can only sub to 1 topic once
> fix(mqtt): shared conn as subtopo

- internal/topo/node/window_v2_op.go
- pkg/ast/visitor.go
> fix(window): state window logic

- internal/topo/node/window_op.go
> fix(checkpoint): gob register map[string]time.time

- contract/api/source.go
> feat(contract): support EoF message

- extensions/impl/sql/source.go
> feat: sql source support pg int4

- internal/topo/node/window_v2_op.go
- internal/topo/node/window_v2_op_test.go
close https://github.com/lf-edge/ekuiper/issues/3847
> feat: support statewindow checkpoint

- internal/topo/planner/planner.go
- internal/topo/planner/planner_sink_test.go
In slice mode, duplicate field is not allowed
> fix(planner): validate duplicate fields

- internal/topo/node/window_v2_op.go
ref https://github.com/lf-edge/ekuiper/issues/3847
> fix: fix window scanner
