xstream/extensions/mqtt_source.go
xstream/sinks/mqtt_sink.go

Fix for #13 
mqtt source and sink close function should check if the connection is existing

fix(extension): runtime error when dropping fail rules

---

docs/en_US/rules/overview.md
docs/en_US/rules/sinks/rest.md
docs/zh_CN/rules/overview.md
docs/zh_CN/rules/sinks/rest.md
xsql/plans/preprocessor.go
xsql/processors/xsql_processor.go
xsql/processors/xsql_processor_test.go
xstream/nodes/sink_node.go
xstream/sinks/mqtt_sink.go
xstream/sinks/rest_sink.go

A sample rule to use for edgex core command:
"{\"sql\": \"SELECT cast(count,\\\"string\\\") as Int8 FROM ext where count > 3\",\"actions\": [{\"rest\":  {\"method\":\"put\",\"url\":\"http://127.0.0.1:48082/api/v1/device/cc622d99-f835-4e94-b5cb-b1eff8699dc4/command/51fce08a-ae19-4bce-b431-b9f363bba705\",\"sendSingle\":\"true\"}}]}"
All fields of the edgex message must be string, so a cast to string for selected field is needed. And the core command only accept a single row, so the sendSingle parameter must be true.

REST sink support

---

xstream/nodes/sink_node.go
xstream/nodes/source_node.go
xstream/operators/operations.go

When restart rule, the previous source/sink instances and their stats should be cleaned up so that they can be recreated with the new config.

bug(stream): restart source should re-read the config

---

docs/en_US/rules/overview.md
docs/zh_CN/rules/overview.md

Gitbook uses `{{ }}` as a built-in template.You need to make sure it's in the markdown code block.

Fix gitbook docs build errors

---

common/kv.go
xstream/nodes/sink_cache.go

1. Save cache one file per rule. So that once the file is corrupted, it only affect one rule.
2. Once cache open fails, automatically drop the content and create a new empty cache file.
#406

fix(sink): sink cache error recovery

---

xstream/cli/main.go

The fix for [issue #413 ](https://github.com/emqx/kuiper/issues/413).

bug: fix cli describe plugin crash issue

---

etc/sinks/properties.json

@jinfahua The `DataTemplate` field is a `textarea` control, which should be of `string` type, not `bool` type.

fix(sinks): fix dataTemplate type to string

---

deploy/docker/Dockerfile-alpine

Currently the kuiper containers run as the root user which is a potential security risk in the event the service is compromised by an attacker. This commit updates all docker files to create a non-password carrying "kuiper" user that runs the container.
Manipulated the dockerfiles to create a kuiper user, set appropriate ownership based on $KUIPER_HOME, and then switch to kuiper user (instead of root) for safe container execution. 
First, follow the steps below to clone the specific branch from my repository, and spin up a kuiper alpine based container. The steps below will drop you into the running container shell.
```
$ git clone --single-branch --branch run-container-as-kuiper-user https://github.com/beaufrusetta/kuiper.git kuiper-pr-test && cd kuiper-pr-test
$ make docker
$ docker run …
```

feat: Run process/container as "kuiper" user

---

docs/en_US/sqls/windows.md

While reading through the docs, I noticed that the markdown was broken in this paragraph:
So I decided to make a quick PR to fix it.

Fix links to window types in windows.md

---

deploy/docker/conf_util.go
deploy/docker/conf_util_test.go
xstream/extensions/edgex_source.go
xstream/extensions/edgex_source_test.go
xstream/operators/preprocessor.go
xstream/planner/dataSourcePlan.go
xstream/planner/planner_test.go
xstream/topotest/mock_topo.go
xstream/topotest/window_rule_test.go

1. Fix the problem: multiple meta fields with only case differences may be retained in message. Should only have one as it is case insensitive.
2. Avoid printing out password in the log in EdgexSource.

fix: do not print out the password in config & meta fields problem

---

common/cast.go
fvt_scripts/edgex/pub.go
fvt_scripts/select_edgex_meta_rule.jmx
xstream/extensions/edgex_source.go
xstream/extensions/edgex_source_test.go
xstream/sinks/edgex_sink.go
xstream/sinks/edgex_sink_test.go

1. Support binary reading
2. In EdgexSink, add type casting when valueType is specified. Need this because edgex typing is very strict
3. Fix a problem in EdgexSource for missing converting string array
4. Fix a problem in EdgexSink for missing reading valueType meta
5. Add test cases for binary type
6. Add FVT test case for binary together in the meta test

feat(edgex):support binary type

---

internal/topo/source/mqtt_source.go

When the MQTT client reconnects, the subscription function may be executed before the connection, resulting in the following error:
**Found error: not currently connected and ResumeSubs not set**
In order to avoid subscription failure, it is best to initiate a subscription after the connection is successful
Of course there might be a better way to do this, but I'm just offering an idea

Fix resubscription failure when reconnecting

---

internal/topo/node/source_node.go
internal/topo/node/source_pool.go

Fix the problem: when source exits by error, the dynamic buffer is not closed

fix(node): should always close dynamic buffer in source node

---

internal/topo/source/httppull_source.go

fix(source httppull): Memory leak when use http source
Should close http connection after read out the body
Add ctx.Done() check in select statement, else will lead to goroutine leak
Close #888 #925

Memory leak when use http pull source

---

internal/topo/operator/join_operator.go
internal/topo/operator/join_test.go

In schemaless mode, the analyzer cannot deduce the stream of a field so that the ref source of a fieldRef could be $$default, which means it could be any of the stream. And that is not a real stream to form a join tuple so we should exclude it.

fix(operator): join tuple must exclude default stream

---

internal/plugin/sourceMeta.go
internal/topo/operator/misc_func_test.go
internal/topo/sink/edgex_sink.go
internal/topo/sink/edgex_sink_test.go
internal/topo/source/mqtt_type.go
internal/topo/source/mqtt_type_test.go
internal/xsql/funcsMisc.go
pkg/cast/cast.go
pkg/cast/cast_test.go

A lot of places are using reflect.TypeOf(i).Kind() to check interface types. If i is nil, the TypeOf may return nil so that this will cause a panic. Fix all potential problems.
Closes: #938

fix(*): reflect.TypeOf must check nil to avoid panic

---

internal/topo/planner/analyzer.go
internal/topo/planner/analyzer_test.go
internal/topo/planner/planner_test.go
internal/xsql/funcsAstValidator_test.go
internal/xsql/parser.go
internal/xsql/parser_test.go
internal/xsql/valuer.go
pkg/ast/expr.go

Currently, a->b are parsed as FieldRef which is the same model as a field. This brings some problems such as field alias may conflict with the json field.
Closes: #945

fix(sql): distinguish json field ref from field ref

---

docs/en_US/rules/sinks/edgex.md
docs/zh_CN/rules/sinks/edgex.md
internal/topo/sink/edgex_sink.go
internal/topo/sink/edgex_sink_test.go
internal/topo/source/edgex_source.go
test/edgex_mqtt_sink_rule.jmx
test/edgex_sink_rule.jmx

- Add messageType for edgeX sink to support send message to message bus like a device
- Change the default configuration to match edgex v2
Closes: #947 #939

fix(edgex): add messageType for sink

---

internal/topo/operator/join_multi_test.go
internal/topo/operator/join_operator.go

Inner join mutliple streams with multiple matches, the matches after the first match will miss the left tuple. Check the test case update for detail.

fix(operator): inner join for multiple streams with multiple matches

---

extensions.sum
extensions/go.mod
extensions/sinks/redis/redis.go

fix(redis sink plugin): use redis v7 lib in redis sink to consistent with edgeX

fix(redis sink plugin): use redis v7 lib in redis sink to consistent with edgeX

---

internal/topo/planner/planner_test.go
internal/xsql/parser.go
internal/xsql/parser_test.go

analyzer and planner rely on the stream name, so must set defaultStream as the default
closes: #972

fix(parser): meta(*) arg must have a stream name

---

docs/en_US/rules/sinks/mqtt.md
docs/en_US/rules/sources/http_pull.md
docs/en_US/rules/sources/mqtt.md
docs/zh_CN/rules/sinks/mqtt.md
docs/zh_CN/rules/sources/http_pull.md
docs/zh_CN/rules/sources/mqtt.md
etc/connections/connection.yaml
etc/mqtt_source.json
etc/mqtt_source.yaml
etc/sinks/mqtt.json
etc/sources/httppull.json
etc/sources/httppull.yaml
internal/pkg/cert/cert.go
internal/pkg/cert/cert_test.go
internal/topo/connection/client_mqtt.go
internal/topo/node/node.go
internal/topo/source/httppull_source.go
internal/topo/source/mqtt_source.go

fix(auth): fix cert auth bug in mqtt and http
1. add rootCaPath config item for mqtt source/sink 
2. add config item to skipVerify Server'cert fot http pull
3. fix regression bug for config_key
Close #1048

fix(auth): fix cert auth bug in mqtt and http

---

internal/plugin/portable/registry.go
internal/plugin/portable/runtime/function.go

1. Currently, nil is return. Change to []
2. Let the function runtime print byte array as string in error

fix(portable): if no plugin, list portable plugins should return []

---

internal/topo/sink/edgex_sink.go

Currently, some types like int8, uint8 etc. are reported as error

fix(edgex): sink should support all type when meta is not specified

---

sdk/python/example/pysam/pyjson.py

Change the python source plugin example to let open run until close

fix(sdk): python source sample should not end source

---

docs/en_US/edgex/edgex_rule_engine_tutorial.md
docs/zh_CN/edgex/edgex_rule_engine_tutorial.md

fix(docs): update edgex tutorial redis kv storage only work in none-ecure mode

---

sdk/go/connection/connection.go
sdk/python/ekuiper/runtime/connection.py

By default, the request will be resent after 1 minute. This makes the timeline in chaos when not receiving data in more than 1 minute.

fix(sdk): disable req resend

---

internal/topo/operator/project_test.go
internal/topo/planner/analyzer.go
internal/topo/planner/planner_test.go
internal/xsql/parser.go
internal/xsql/parser_test.go
pkg/ast/expr.go

All fields now will have either a field name or an alias name

refactor(parser): assign field name in the parser side

---

internal/plugin/portable/runtime/connection.go
internal/plugin/portable/runtime/plugin_ins_manager.go
sdk/go/connection/connection.go
sdk/go/runtime/plugin.go
sdk/python/ekuiper/runtime/connection.py

1. Make sure control channel closed in error
2. Separate handshake timeout and receive timeout
3. Do not pose timeout after handshake, to design later

fix(portable): clean up portable plugin instance

---

docs/en_US/extension/native/develop/sink.md
docs/zh_CN/extension/native/develop/sink.md
internal/binder/function/funcs_misc.go
internal/topo/context/default.go
internal/topo/context/default_test.go
internal/topo/memory/sink.go
internal/topo/sink/mqtt_sink.go
internal/topo/sink/rest_sink.go
pkg/api/stream.go

Put these conversion functions in context to be able to save the parsed result instead of do the parsing everytime. And the cache parsed result can be auto managed as part of the context lifecycle.

feat(rule): separate context method for template and jsonPath

---

internal/schema/protobuf/converter.go
internal/schema/protobuf/converter_test.go
internal/schema/protobuf/fieldConverterSingleton.go
internal/schema/registry.go
internal/schema/registry_test.go
internal/schema/schema.go
internal/server/schema_init.go
internal/service/schema.go
internal/topo/node/sink_node.go
internal/topo/node/sink_node_test.go
internal/topo/sink/rest_sink_test.go
internal/topo/transform/template.go
pkg/message/decode.go

1. Support protobuf 'format' in sink, must use with 'schemaId' together
2. Refactor protobuf schema encoder to be shared between external service and sink format
#1267

feat(sink): support general property 'format'

---

internal/topo/connection/clients/mqtt/client_mqtt_test.go
internal/topo/connection/clients/mqtt/mqtt.go

also add debug log to paho if debug is enabled

refactor(mqtt): default to MQTT 3.1.1(4) to connect to NanoMQ

---

docs/zh_CN/CONTRIBUTING.md
docs/zh_CN/quick_start_docker.md

- quick_start_docker.md：推荐使用的 MQTT 客户端工具博客地址失效，修改为正确的访问地址。
- CONTRIBUTING.md: Sifnoff 修改为 Signoff。
#1362

docs(zh_CN): 失效的引用地址，错误的单词拼写

---

internal/xsql/row.go

toMap may be accessed by multiple go routines.

fix(runtime): add lock to toMap

---

internal/topo/operator/project_test.go
internal/topo/planner/planner_test.go
internal/topo/topotest/rule_test.go
internal/xsql/parser.go
internal/xsql/parser_test.go

feat(sql): support wildcard with other selects

---

deploy/docker/README.md
docs/en_US/extension/native/develop/plugins_tutorial.md
docs/en_US/operation/manager-ui/overview.md
docs/en_US/operation/manager-ui/plugins_in_manager.md
docs/zh_CN/extension/native/develop/plugins_tutorial.md
docs/zh_CN/operation/manager-ui/overview.md
docs/zh_CN/operation/manager-ui/plugins_in_manager.md

fix(docs): update docs docker image

---

internal/xsql/row.go

It is possible to have multiple sinks call ToMap at once

fix(row): add lock for ToMap to avoid concurrent map write

---

internal/plugin/portable/manager.go
internal/plugin/portable/runtime/connection.go
internal/plugin/portable/runtime/connection_test.go
internal/plugin/portable/runtime/function.go
internal/plugin/portable/runtime/plugin_ins_manager.go
internal/plugin/portable/runtime/plugin_ins_manager_test.go
internal/plugin/portable/runtime/shared.go
internal/plugin/portable/runtime/sink.go
internal/plugin/portable/runtime/source.go
tools/plugin_server/plugin_test_server.go

When deleting portable plugin, the rules are kept running. When recreating the plugin, the rule will recover automatically
This is done by record the symbol commands and replay when new plugin instance starts.

opt(portable): hot reload support

---

internal/topo/operator/analyticfuncs_operator_test.go
internal/xsql/row.go
internal/xsql/row_test.go

fix(row): do not write out the internal fields for join tuple for 1.8

---

internal/plugin/portable/runtime/plugin_ins_manager.go

The instance may be initialized twice as the command list cannot guarentee to be updated before next symbol starting

fix(portable): fix restart rule with multiple portable symbol reference

---

internal/topo/planner/planner_test.go
internal/topo/planner/windowPlan.go

Not time window will depend on the events, so should not filter any before running window op

fix(planner): do not move predicate for sliding window

---

internal/topo/mock/test_source.go
internal/topo/source/file_source.go
internal/topo/source/file_source_test.go
internal/topo/source/test/test.lines

Typical usage json lines file.
Also support binary lines file like protobuf serialization lines

feat(source): file source add support for lines format

---

internal/service/manager.go

Signed URLs like this will fail to register，But it's a valid URL
http://xxx:8080/AA/functions/ExecJobService.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20230103%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230103T085455Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=3edf9ce46eea9e0da5e60f25b89c0751311f46683a5507639a3dfe7d7601fe43

Solve the problem of registering an external service reporting invalid file path

---

internal/converter/converter.go
internal/converter/ext_converter.go
internal/schema/ext_inferer_custom.go
internal/schema/ext_inferer_custom_test.go
internal/schema/inferer.go

It depends on plugin framework which will add 2MB+ to the core binary

refactor: move custom schema out of core

---

internal/topo/rule/ruleState.go

Fix the problem when rule stops by error, topo is not refreshed at starting

fix(rule): must reload topo when rule start

---

README.md

Hi,
I've found the project while studying EdgeX docs and noticed that the quick start link is broken. Here is a fix :)
Have a good day!

readme: fix link to quick start

---

docs/en_US/configuration/global_configurations.md
docs/zh_CN/configuration/global_configurations.md
etc/kuiper.yaml
internal/conf/conf.go
internal/plugin/portable/runtime/connection.go
internal/plugin/portable/runtime/connection_test.go

Some plugin, especially when loaded AI models, need a lot of init time

feat(conf): allow to set portable init timeout value

---

docs/en_US/extension/native/develop/plugins_tutorial.md
docs/zh_CN/extension/native/develop/plugins_tutorial.md

In version 1.9.0, the go workspace feature is used to refactor the go mod build of the submodules, so the plugin tutorial documentation needs to be updated.

fix (doc): update plugin tutorial doc

---

internal/binder/function/funcs_misc.go
internal/binder/function/funcs_stateful.go
internal/binder/function/funcs_stateful_test.go
internal/binder/function/function.go
internal/binder/function/static_executor.go
internal/compressor/compressor.go
internal/xsql/functionRuntime.go
pkg/message/artifacts.go

1. Add a new built in function type stateful function, which has state. The function runtime can guarantee each func id in operator level will have only one function instance.
2. Add the compressor package to manage compress methods
3. Refactor function binder, split static executor and support stateful function instantiation

feat(func): add compress function

---

internal/topo/connection/clients/mqtt/mqtt_wrapper.go

The default connection state is set to false and suppose to be sync by connect callback. It seems it is possible that the connect callback runs after publish so the first publish check conn return error.
Closes #1716

fix(mqtt): sync mqtt connection state

---

.github/workflows/lint.yaml

This check while pushing to fork branch always return an error and an error email. We only allow pr to merge code, it is not mandatory to check in push, so remove it

fix(ci): remove lint check in push

---

internal/io/http/rest_sink.go
internal/io/http/rest_sink_test.go

Only return io error can trigger the cache mechanism
closes #1768

fix(sink): reset sink to return io error if network problem happens

---

internal/topo/rule/ruleState.go
internal/topo/rule/ruleState_test.go

Make the rule state the same for better presenting in the manager rule list.
- Stopped rule, when loaded after restart, set to the same state as rule just stopped.

refactor(rule): unify rule state for stopped rules

---

pkg/ast/sourceStmt_test.go
pkg/cast/cast_test.go
sdk/go/example/mirror/random_source_test.go

Logf formats its arguments according to the format, analogous to Printf, and records the text in the error log. A final newline is added if not provided.

chore: use `t.Logf` in unit tests

---

internal/io/http/rest_sink_test.go
internal/server/rpc.go

This PR fixes a potential printing issue in printf-style functions with dynamic format strings.
e.g., when dynamic format string contains strings like `%s` will cause unexpected problems.

fix: use print-style functions

---

internal/processor/stream.go
internal/server/rest.go

`strings.Title` has been deprecated since Go 1.18. Use golang.org/x/text/cases instead.

refactor: replace strings.Title with cases.Title

---

internal/topo/rule/ruleState.go

`time.Tick` leaks the underlying ticker and should only be used in endless functions.

fix(topo): gc leaks with time.Tick

---

Makefile

This PR fixes a potential situation where a user might not have `curl` installed.

chore(lint): replace curl with go install

---

.github/workflows/run_fvt_tests.yaml
.github/workflows/run_test_case.yaml

When writing unattended scripts (including Dockerfiles), when `using apt install -y` but without `DEBIAN_FRONTEND=noninteractive`, sometimes installation will get stuck at an interactive prompt.

ci(tests): fix a potential apt hanging

---

.github/workflows/run_fvt_tests.yaml

apt does not have a stable CLI interface.

ci(fvt-tests): replace apt with apt-get

---

extensions/sinks/sql/sql.go
extensions/sinks/sql/sql_test.go
extensions/sqldatabase/db.go
extensions/sqldatabase/mock.go

Because double quote is recognized as column by pgsql

fix(sql): update sql should use single quote literal

---

internal/topo/operator/filter_operator.go
internal/topo/operator/filter_test.go
internal/topo/topotest/window_rule_test.go

When all rows are filtered, stop propagation to next op

fix(op): filter collection should stop propagation

---

.github/workflows/run_test_case.yaml

Setting the `fail_ci_if_error` option to true will mark the whole test CI as failed if uploading process is temporarily unavailable.
Turning this option off is recommended (as `false` is the default value by codecov).

ci(codecov): avoid needless ci failure

---

.github/workflows/build_packages.yaml

options description:
- `-f`: non-zero exit code if http failed
- `-v`: enable verbose mode
- `-s`: silent mode to suppress curl's progress bar

ci(release): fail release with update errors

---

internal/server/rest_test.go
internal/server/rule_manager.go

let startRule rerun the rule in order to re-optimize the rule, then we can generate the plan with the latest schema.

feat: let `startRule` rerun the rule

---

.github/dockerfile/Dockerfile.debian
.github/workflows/build_base_image.yaml
deploy/docker/Dockerfile-slim

This PR upgrades all debian-based images to `bullseye` release. The [stretch](https://hub.docker.com/layers/library/debian/stretch/images/sha256-16ee3e11da473f6565ef94a715f1a38b3079e0664913be78869c336a71cb6085?context=explore) release is no longer maintained and supported by debian official docker image.

ci(docker/debian): upgrade debian to bullseye

---

internal/topo/planner/planner_test.go
pkg/ast/visitor.go

```
SELECT *,  CASE WHEN ts - lag(ts) OVER (WHEN temperature < 0 AND lag(temperature) > 0) BETWEEN 1000 AND 1100 THEN 1 ELSE 0 END AS condition FROM mockStream
```
In the given example, the presence of only a "when" clause implies that the "walk" function needs to account for this specific case.

fix: fix walk function

---

internal/pkg/store/redis/redisKv.go

Previously rediskv get function returned an error when the specified key was not found,however the corresponding sqlite implementation returned a boolean specifying value was not found however no error was returned.
This commit copies the sqlitekv behaviour into rediskv.
for sqlite
for redis
The reason why i had to do this change is ,when we use native function plugins, i tried the sample echo function, when ekuper starts the initmanager tries to get a keyvalue for the corresponding function.Ekuper was working fine when i used sqlite as memory store.However when i switched to redis , i was getting an error ("error when querying kv:)  and ekuper used to panic and didnt start.
This was done to copy the sqlite behavior into the rediskv
Manager

fix: rediskv get return

---

cmd/kuiper/main.go
internal/binder/function/funcs_misc.go
internal/conf/jsonpath_eval.go
internal/hack/hack.go
internal/hack/hack_test.go
internal/io/edgex/edgex_source.go
internal/io/http/client.go
internal/io/redis/lookup.go
internal/meta/yamlConfigMeta.go
internal/plugin/native/manager.go
internal/plugin/portable/manager.go
internal/processor/rule.go
internal/processor/stream.go
internal/schema/ext_inferer_custom.go
internal/schema/registry.go
internal/server/rpc_plugin.go
internal/server/rpc_schema.go
internal/server/rpc_service.go
internal/service/manager.go
internal/topo/operator/field_processor.go
internal/xsql/stmtx.go
pkg/cast/hack.go
pkg/cast/hack_test.go

This submission implements a performance optimization for JSON parsing by avoiding the copying of strings into byte arrays.

perf: Avoid string copying during JSON parsing

---

cmd/kuiperd/main.go
go.mod
go.sum

Go processes usually set the max proc num from the value of `runtime.NumCPU()`, but this function cannot return real/correct cpu limits with certain cgroups settings (e.g. docker, k8s resource limits), which may causes the GMP model running inefficiently and impacts the performance.
This PR uses the uber's [automaxprocs](https://github.com/uber-go/automaxprocs) pkg to automatically and correctly set the max cpu processor numbers that honors cgroups settings.
Ref: https://segmentfault.com/a/1190000043930543

feat: honor cpu limits in cgroups

---

cmd/kuiper/main.go
extensions/sinks/tdengine/tdengine.go
internal/io/http/httpserver/data_server.go
internal/pkg/store/redis/redis.go
internal/server/rest.go
internal/server/rpc.go
internal/server/server.go
pkg/cast/net.go
pkg/cast/net_test.go
tools/kubernetes/util/util.go
tools/plugin_server/plugin_test_server.go

`fmt.Sprintf(%s:%d)` cannot correctly handle IPv6 addresses because IPv6 addresses require to be enclosed in square brackets like:
- `[2001:db8::1]:8080`
This is what is being used in URLs for example:
- `http://[2001:db8::1]:8080/`
Using go's `net.JoinHostPort` can solve this kind of issue.
- Fixes #2029

fix: correctly concatenate ipv6 addr

---

internal/io/http/httpserver/data_server.go

Fixes #2027 
The done channel is a global variable. createDataServer function is covered by a mutex, but the part that closes the channel is in a different goroutine - which isn't tracked.
This can lead to the following race condition:
1. createDataServer called.
2. UnregisterEndpoint called. The goroutine from createDataServer wasn't called yet.
3. createDataServer called. The goroutine from the first createDataServer is called now, and it just closed the new done channel.
4. UnregisterEndpoint called. The goroutine from the second createDataServer is called now, and it closes a closed channel - panic.
The solution is to pass the done channel to the goroutine scope.

fix(source): race-condition at httpserver

---

internal/schema/inferer.go
internal/schema/inferere_test.go

Should not return error if schema cannot be inferred.

fix(schema): allow weak schema type

---

internal/xsql/collection.go
internal/xsql/row.go
internal/xsql/row_test.go

rule:
```
select collect(*), a AS ab from demo GROUP BY ab, TUMBLINGWINDOW(ss, 10);
```
output:
```
{
"ab": 2
"collect": [{"a": 2, "ab": 2, "b": 1}]
}
```
This pr is primarily aimed at addressing the issue.

fix: wildcard contains alias

---

.github/workflows/run_test_case.yaml

Use 0.12.1 instead of master
When they updating version, master may have problems.

chore: fix wasm edge version

---

docs/en_US/sqls/functions/mathematical_functions.md
docs/zh_CN/sqls/functions/mathematical_functions.md
internal/binder/function/funcs_array_test.go
internal/binder/function/funcs_math.go
internal/binder/function/funcs_math_test.go

Added some common MySQL/PostgreSQL-style math functions and its aliases.
Refer to: 
- https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html
- https://www.postgresql.org/docs/9.1/functions-math.html

feat(math): add common SQL math funcs/aliases

---

.github/workflows/run_test_case.yaml

This PR aims for fixing the unstable uploading issue with Codecov.
The reason for the failed uploads is due to Codecov’s inability to check the validity of a coverage upload when using tokenless uploads. The underlying issue is rate-limiting from GitHub.
Adding the [Codecov upload token](https://docs.codecov.com/docs/codecov-uploader#upload-token) into GitHub Secrets will solve this issue in most cases even if the project is public.
> The issue is still ongoing, and we are taking steps to decrease our GitHub API use. At this point, we **strongly recommend** using the Codecov upload token to upload to Codecov.
Ref: https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954

ci(codecov): fix upload issue with explicit token

---

docs/en_US/sqls/functions/transform_functions.md
docs/zh_CN/sqls/functions/transform_functions.md
internal/binder/function/funcs_misc.go
internal/binder/function/funcs_misc_test.go

This PR adds a MySQL-style [`to_seconds`](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_to-seconds) function that converts a datetime to its unix seconds form.

feat(sql): add `to_seconds` function

---

internal/topo/operator/preprocessor.go
internal/topo/operator/preprocessor_test.go

Previously, only apply timestamp format when schema is set. Extend it to all cases.

fix(source): always apply timestamp format

---

internal/server/server.go

exit process after an error occurs like bind failed "bind: address already in use"
Signed-off-by: ke4nec <ke4nec@qq.com>

fix: exit process after an error occurs

---

internal/conf/conf.go
internal/io/mqtt/mqtt_sink.go
internal/topo/node/cache/sync_cache.go
internal/topo/node/cache/sync_cache_test.go
internal/topo/node/sink_node.go
internal/topo/node/sink_node_test.go
internal/topo/topotest/mocknode/mock_resend_sink.go
pkg/api/stream.go

Allow sending failure data in another queue to separate data from the normal sink
- In SinkNode, add a resend queue if configured
- Add ResendSink interface, which can implement a function for resend collect.
- Use MQTT sink as an example, implement CollectResend

feat(sink): support resend queue

---

Makefile

For `kuiper` cli tool, CGO is useless so disabled. `Trimpath` is added to remove redundant path info.

chore: improve makefile for building kuiper cli

---

docs/en_US/sqls/functions/other_functions.md
docs/zh_CN/sqls/functions/other_functions.md
internal/binder/function/funcs_misc.go
internal/binder/function/funcs_misc_test.go
internal/topo/context/default.go
internal/topo/operator/misc_func_test.go
internal/topo/topo.go

feat(func): add rule_start()

---

internal/conf/conf.go
internal/server/rest.go

This PR will fix an issue when updating from:
- consoleLog: true
- fileLog: false
to:
- consoleLog: false
- fileLog: true
that console log cannot be disabled due to a logic flaw in the previous code.

fix: avoid log override when update

---

internal/pkg/store/redis/redisTs.go
internal/pkg/store/sql/sqlTs.go
internal/topo/node/join_align_node.go
internal/topo/operator/table_processor.go
internal/topo/topotest/checkpoint_test.go
internal/xsql/gob_register.go
internal/xsql/row.go
sdk/go/context/default.go

Scan table saves state data with an interface type which cannot encode/decode by gob
Closes #2111

fix: scan table join checkpoint

---

internal/binder/function/funcs_array.go

Fix the problem that array_shuffle would change the original array data.

fix(func): array_shuffle should clone

---

internal/binder/function/funcs_array.go
internal/binder/function/funcs_array_test.go

Fix the problem of panic when running against an embedded array

fix(func): array distinct ignore un-hashable

---

internal/topo/graph/io.go

问题：
使用graph rule时，同时包含join和script节点会报类型错误
解决办法：
将script io input改为any
Signed-off-by: Pengfei Liu <261223363@qq.com>

fix(operator): script Type->IOINPUT_TYPE_ANY

---

extensions/go.mod
extensions/sqldatabase/driver/apply.go
extensions/sqldatabase/driver/databend.go
go.work.sum

- fix https://github.com/lf-edge/ekuiper/issues/2178
I found that databend has already been added into [dburl](https://github.com/xo/dburl), so it is very convenient to support it as a sink. BTW, how can I add some integration tests for databend sink?

feat(sink): support databend as sink

---

etc/sinks/redisPub.json
etc/sources/redisSub.json
etc/sources/redisSub.yaml
internal/binder/io/ext_redis.go
internal/io/mock/context/mock.go
internal/io/redis/pubsub/redisPub.go
internal/io/redis/pubsub/redisPub_test.go
internal/io/redis/pubsub/redisSub.go
internal/io/redis/pubsub/redisSub_test.go
internal/io/redis/pubsub/redis_test.go

Add two new builtin connectors.
redisSub Source:
Add a new data source called "redisSub." This source empowers users to subscribe to specific Redis channels and stream received messages into Ekuiper. Configuration parameters are included to specify the Redis server and the channel to subscribe to.
redisPub Sink:
Add a new data sink called "redisPub." The redisPub sink allows users to publish data from Ekuiper to a designated Redis channel. Configuration parameters are included to specify the Redis server and the target channel.
Bug Fix:
Resolve a bug encountered during testing of the redisPub sink with ctx.TransformOutput() using a mock context at mock.RunSinkCollect(). The bug is fixed by adding context.TransKey to the context.NewMockContext(), ensuring that testing ctx.TransformOutput() …

feat: add redisSub source and redisPub sink

---

cmd/kuiper/main.go
internal/processor/stream.go
internal/processor/stream_test.go

Add ability to get output from describe as json format.
Closes: [#186](https://github.com/lf-edge/ekuiper/issues/186)
I added a converter to parse the regular describe return val. I did this so as not to pass a flag all the way down, also not to potentially impact anything else in other places uses the `execDescribe` - since that method outputs a predictable format I just added a parses to convert it to json.
examples:
* No Flag
`go run main.go describe stream topic`
Fields
--------------------------------------------------------------------------------
USERID  bigint
FIRST_NAME      string
LAST_NAME       string
NICKNAMES       array(string)
Gender  boolean
ADDRESS struct(STREET_NAME string, NUMBER bigint)
DATASOURCE: users
FORMAT: JSON
KEY: USERID
* With flag
`go run main.go describe …

feat: add -json flag to describe

---

internal/io/http/client.go
internal/io/http/httppull_source_test.go
internal/io/http/rest_sink.go
internal/io/http/rest_sink_test.go

When debugResp is true, we will parse the response once data sent out. Currently, the error in parsing returns to the rule which is not part of the action.
Relates to #2343

fix(sink): rest sink not return response error

---

internal/topo/planner/planner_test.go
pkg/ast/visitor.go

Analytic functions are not lifted when using in case when value expr. The root cause is that visitor miss to visit value expr.

fix(planner): analytic in case value expr

---

internal/io/file/file_writer.go
internal/io/file/writer/bufioall.go

File sink should not truncate files even in the middle of writing.
Closes #2343

fix(sink): file sink flush as a whole

---

docs/en_US/concepts/ekuiper.md

Changed "written on" Go to "written in go"

docs: fix syntax error in readme

---

internal/io/memory/pubsub/manager.go
internal/topo/rule/ruleState.go
internal/topo/topo.go
pkg/infra/saferun.go

1. fix goroutine leak when stop rule in `runTopo`
2. de-reference old Topo in order to release memory after stop/close rule
3. close channel to release memory after `removePub`

fix: fix memory leak when stop rule

---

internal/trial/run.go

Rule id is part of many id, conflict between multiple trial rules or real rule may happen. Add a prefix and uuid for each trial rule runtime id.

fix(trial): avoid rule id conflict

---

docs/en_US/sqls/functions/object_functions.md
docs/zh_CN/sqls/functions/object_functions.md
internal/binder/function/funcs_obj.go
internal/binder/function/funcs_obj_test.go

The function signature of object_pick, which was mentioned in #2530, has changed slightly to keep consistent with the erase function.

feat: support object_pick function

---

internal/binder/function/funcs_datetime.go
internal/binder/function/funcs_obj.go

Fix args validation of `date_calc` and typo error in funcs_obj.go
Close https://github.com/lf-edge/ekuiper/issues/2568

fix(functions): args validation of `date_calc`

---

docs/zh_CN/guide/sources/builtin/neuron.md

Correct an error in the Chinese documentation describing the Neuron connector configuration.
Closes #2611

fix(docs): correct typo

---

internal/binder/function/funcs_math.go
internal/binder/function/funcs_math_test.go

fix(func): fix ln function

---

internal/service/manager.go
internal/service/manager_test.go

Fix delete schemaless service but the func are still listed problem. The root cause is that the schemaless func are not recorded in the service.

fix(service): delete schemaless func

---

internal/topo/node/cache/sync_cache.go
internal/topo/node/sink_node.go

When messages are dropped in the sink node, add logs.

chore: add message ignore log

---

internal/topo/topo.go

Update open state when cancel
This leads to a problem in trial run because it

fix(topo): avoid wrong topo open state

---

internal/topo/rule/ruleState.go

The topo creation may panic when recover rule. Do not let it return a nil rs in such case. Otherwise, read rule status will panic the server.

fix(topo): catch recover rule error

---

docs/zh_CN/sqls/functions/string_functions.md

substring function not support Negative integer

docs: fix Chinese doc errors for substring func

---

extensions/sinks/tdengine/ext/tdengine.go

fix: tdengine plugins rules stopped when fields not in streams
fix: tdengine tags not in fields sqlbuild error (#2668)
Closes #2668

fix: tdengine fields setting problem

---

internal/topo/node/conf/source.go
internal/topo/planner/planner.go

If other source node has error, subtopo should not be created. For example, if decode validation fails with error, subtopo should not be created.

fix(planner): avoid create subtopo in error

---

docs/en_US/api/restapi/streams.md
docs/en_US/api/restapi/tables.md
internal/processor/stream.go
internal/server/rest.go
internal/server/rest_test.go

Instead of returning name of tables and streams, we can return xsql.StreamInfo directly.

feat: add 'format' and 'type' fields in list apis

---

.github/workflows/lint.yaml

This PR mainly updates `golangci-lint-action` to v6, and also automatically specifies the go version from `go.mod` for further convenience.

ci(lint): bump `golangci-lint-action` to v6

---

internal/conf/yaml_config_storage.go
internal/server/bump/bump3.go
internal/server/bump/bump3_test.go
internal/server/bump/bump_manager.go

bump sql source configuration from :
```yaml
default:
interval: 10000
url: mysql://user:test@140.210.204.147/user?parseTime=true
internalSqlQueryCfg:
table: test
limit: 1
indexField: registerTime
indexValue: "2022-04-21 10:23:55"
indexFieldType: "DATETIME"
dateTimeFormat: "YYYY-MM-dd HH:mm:ss"
templateSqlQueryCfg:
TemplateSql: "select * from table where entry_data > {{.entry_data}}"
indexField: entry_data
indexValue: "2022-04-13 06:22:32.233"
indexFieldType: "DATETIME"
dateTimeFormat: "YYYY-MM-dd HH:mm:ssSSS"
```
into
```yaml
default:
interval: "10s"
dburl: mysql://user:test@140.210.204.147/user?parseTime=true
internalSqlQueryCfg:
table: test
limit: 1
indexFields:
- indexField: registerTime
indexValue: "2022-04-21 10:23:55"
indexFieldType: "DATETIME"
dateTimeFormat: "YYYY-MM-dd HH:mm:ss" …
```

feat: support bump sql source conf

---

internal/topo/operator/filter_test.go
internal/topo/operator/join_test.go
internal/xsql/valuer.go
internal/xsql/valuer_test.go
pkg/ast/token.go

- For binary comparison, null value always return false
- In/NotIn should always return bool (or error)

fix(valuer): nil handling

---

internal/io/file/reader/csv.go
internal/io/file/reader/lines.go
internal/io/file/source.go
internal/io/file/source_test.go
pkg/modules/file.go

Currently, if line is big, the lines scanner exit silently

fix(file): scanner dynamic buffer

---

internal/server/meta_init.go

fix https://github.com/lf-edge/ekuiper/issues/2981

fix: fix the bad variable reference

---

internal/topo/planner/planner_source.go
internal/topo/planner/planner_source_test.go

- If merger does not set payload format, use the message format and schema

feat(planner): set default payload format

---

extensions/impl/zmq/source.go
extensions/sources/zmq/zmq.go
internal/conf/path.go
internal/plugin/native/manager.go
internal/plugin/portable/manager.go
internal/plugin/portable/manager_test.go
internal/topo/node/node.go
internal/topo/node/source_node.go
internal/topo/topo.go
test/prepare_plugins.sh
test/run_jmeter.sh

- Fix plugin config install
- Fix zmq plugin subscribe
- Fix jmeter tests

fix(native): fix plugin config install

---

internal/topo/topotest/mock_topo.go
internal/topo/topotest/plugin_rule_test.go

fix(test): plugin result comparison

---

go.mod
go.sum
internal/server/promMetrics/core_metrics.go
internal/server/promMetrics/prom_metrcis.go
internal/server/rule_init.go
internal/server/server.go
internal/server/server_test.go

By introducing the feature of observing cpu usage in a specified time window provided by the cpuprofile library, we can now observe the cpu usage of each rule of ekuiper through prometheus.
To use this feature, you need to set prometheus and enableResourceProfiling in the configuration file to true.
Then, run ekuiper and use [test tool](https://github.com/Yisaer/kuiper-nexmark-test) as shown below:
You can observe rule cpu usge in prometheus as shown below:

feat: prometheus view rule cpu usage

---

internal/io/mqtt/client/client.go

The onConnect may call after publish thus, the connection status is not sync when publishing. This will fail publish.

fix(mqtt): publish random fail at startup

---

.github/workflows/run_fvt_tests.yaml
Makefile
deploy/docker/Dockerfile-full
extensions/impl/zmq/conf.go
extensions/impl/zmq/sink.go
extensions/impl/zmq/source.go
internal/binder/io/ext_full.go
internal/binder/io/ext_full_nowin.go
test/lookup_table_sql.jmx
test/plugin_end_2_end.jmx
test/prepare_plugins.sh

avoid random panic when rule stops and receive is still running

refactor(zmq): add timeout for receive

---

docs/en_US/api/restapi/connection.md
docs/zh_CN/api/restapi/connection.md
extensions/impl/influx/influx.go
extensions/impl/influx2/influx2.go
extensions/impl/kafka/sink.go
extensions/impl/kafka/source.go
extensions/impl/zmq/sink.go
extensions/impl/zmq/source.go
fvt/conn_test.go
fvt/sdk.go
internal/server/rest.go
internal/topo/subtopo.go
pkg/connection/conn.go
pkg/connection/pool.go

Fix problems for shared stream with shared connection id

fix(conn): connection status for shared stream

---

internal/io/simulator/simulator.go
internal/trial/manager.go
internal/trial/manager_test.go
internal/trial/run.go

The control websocket is closed immediately once rule ends. This has problem if simulator has EOF
1. The mirror websocket is not created by pool. The rule stop can close the mirror control ws.
2. EOF will stop the rule immediately before user click stop. In trial run, EOF will not close mirror ws immediately to wait for user click.

fix(trial): do not close control ws

---

go.mod
go.sum

The v2.8.21 version does not support 32 bit

chore: downgrade go-ora

---

cmd/kuiperd/main.go

Because MSSQL driver is not compatible with go 1.23, need to enable this param

chore: enable x509negativeserial

---

.github/workflows/build_packages.yaml
Makefile
deploy/docker/Dockerfile-alpine-python

**Motivation:**
When running Edgex in secure mode it uses securitty-bootstrapper which has been compiled in Alpine Linux. 
Thus, using any other docker image than ekuiper-alpine fails because it cannot run the aforementioned binary.
**Suggested solution:**
Make a eKuiper python Alpine based docker image to be able to use python based plugins
**Tests:**
Tested and running successfully using ekuiper v1.14.4

build: Dockerfile-alpine-python and Makefile build

---

internal/io/http/client.go
internal/io/http/httppull_source.go
internal/io/http/rest_sink.go
internal/io/http/rest_sink_test.go
internal/pkg/httpx/http.go
internal/service/executors.go

Support multiple formats like csv

refactor(rest): convert to byte collector

---

docs/en_US/api/restapi/trace.md
docs/zh_CN/api/restapi/trace.md
internal/io/mqtt/source.go
internal/io/neuron/sink.go
internal/io/neuron/source.go
internal/server/rest.go
internal/server/rule_init.go
internal/server/tracer_test.go
internal/topo/context/default.go
internal/topo/node/batch_op.go
internal/topo/node/operations.go
internal/topo/node/tracenode/trace_node.go
internal/topo/node/transform_op.go
internal/topo/node/window_op.go
internal/topo/rule/state.go
internal/topo/topo.go

support trace strategy `head`/`always`
1. `head` will check whether the source request has trace parent if enabled
2. `always`will always trace if enabled

feat: support trace strategy

---

internal/topo/node/batch_op.go
internal/topo/node/cache_op.go
internal/topo/node/compress_op.go
internal/topo/node/concurrent.go
internal/topo/node/decode_op.go
internal/topo/node/decompress_op.go
internal/topo/node/dedup_trigger_op.go
internal/topo/node/encode_op.go
internal/topo/node/encrypt_op.go
internal/topo/node/event_window_trigger.go
internal/topo/node/join_align_node.go
internal/topo/node/lookup_node.go
internal/topo/node/node.go
internal/topo/node/operations.go
internal/topo/node/rate_limit.go
internal/topo/node/sink_node.go
internal/topo/node/source_node.go
internal/topo/node/switch_node.go
internal/topo/node/transform_op.go
internal/topo/node/watermark_op.go
internal/topo/node/window_op.go

Make it possible to add common hook functionalities for all nodes

refactor(node): extract process start/end hook

---

internal/topo/node/batch_op.go
internal/topo/node/cache_op.go
internal/topo/node/concurrent.go
internal/topo/node/decode_op.go
internal/topo/node/dedup_trigger_op.go
internal/topo/node/encode_op.go
internal/topo/node/event_window_trigger.go
internal/topo/node/join_align_node.go
internal/topo/node/lookup_node.go
internal/topo/node/node.go
internal/topo/node/operations.go
internal/topo/node/rate_limit.go
internal/topo/node/sink_node.go
internal/topo/node/source_node.go
internal/topo/node/switch_node.go
internal/topo/node/tracenode/trace_node.go
internal/topo/node/transform_op.go
internal/topo/node/watermark_op.go
internal/topo/node/window_op.go
internal/topo/operator/projectset_operator.go
internal/xsql/collection.go

- In node hook start functions, only record data when ingesting (the output data will be recorded as the input/data of the next operatore).
- also trace error

refactor(trace): move trace into common func

---

internal/conf/logger/logger.go

When both fileLog and consoleLog are disabled, should discard the log.

fix(logger): discard log if disabled

---

docs/en_US/edgex/edgex_rule_engine_command.md
docs/zh_CN/edgex/edgex_rule_engine_command.md

fix(docs): fix null check

---

internal/io/file/source.go

The file buffer may be wrong due to bytes are not copied

fix(io): file source ignore endLine buffer

---

fvt/rulestate_test.go
fvt/sdk.go
internal/server/rule_manager.go
internal/topo/planner/planner_source.go
internal/topo/rule/state.go
internal/topo/rule/state_test.go

validate may plan topo but not run if rule is not triggered. This will lead to buffer full if the source is a shared source.

fix(state): untriggerd rule always cancel

---

internal/io/mqtt/client/client.go

fix(io): mqtt subscription concurrent map

---

extensions/sources/sql/ext/sql.go
extensions/sources/sql/ext/sqlLookup.go
internal/topo/node/sink_node.go

1. Fix sink buffer length metrics
2. SQL source close rows after read

fix(sink): fix sink buffer length metrics

---

extensions/sinks/kafka/ext/kafka.go
internal/topo/node/node.go
internal/topo/node/sink_node.go
internal/topo/planner/sink_planner.go
pkg/api/stream.go

1. support wait channel when buffer full option
2. revise kafka sink batch configure

feat: wait channel when buffer full option

---

internal/server/rpc_plugin.go

fix(cli): modify nil != nil bug

---

internal/topo/node/cache/sync_cache.go

The cache are: [memCache disk bufferWritePage], if disk or bufferWritePage already exist, do not write to memCache

fix(cache): add to disk cache already have some

---

internal/binder/function/funcs_analytic.go
internal/topo/operator/analyticfuncs_operator_test.go
internal/topo/operator/misc_func_test.go

This is a breaking change. But in most cases in IoT, null just mean the same value as the previous one. So just ignore it.

feat(func): lag ignoreNull defaults to true

---

extensions/impl/kafka/sink.go
extensions/impl/kafka/sink_test.go
internal/testx/testUtil.go
internal/topo/planner/planner_sink.go
pkg/model/io.go

- Move batch implementation into Kafka sink itself
- Support template in batch
- Support different encode format besides json

refactor(kafka): change to byte collector

---

.github/workflows/build_base_image.yaml
.github/workflows/build_packages.yaml
deploy/docker/Dockerfile-slim-python

- Use Github native arm runner to run arm64 binary (non-docker) build. Remove armv7 binary support
- Use ubuntu runner version 24.04 + qemu latest 9.2.2
- Update python version and fix incompatibility
- Slim-python docker file refactor to 3 layers, build pip in python-builder layer

refactor(build): native arm and qemu update

---

extensions/impl/sql/sink.go
extensions/impl/sql/sink_test.go
internal/topo/planner/planner_sink.go
pkg/model/io.go

Some sink need to handle common properties by itself instead of delegate to the transform op or other sink splitted op

fix(planner): sql sink should handle fields

---

internal/topo/rule/state.go

A regression caused by EOF source handling. Manual stop should not change state twice, only change state when error happen or EOF happen.

fix(rule): manual stop state

---

fvt/rulestate_test.go
internal/io/mqtt/source_sink_test.go
internal/io/mqtt/v5_test.go
internal/pkg/def/rule.go
internal/processor/rule.go
internal/processor/ruleset.go
internal/server/import_export.go
internal/server/rest.go
internal/server/rule_init.go
internal/server/rule_manager.go
internal/server/rule_manager_test.go
internal/topo/node/join_align_node_test.go

- Rule add version property
- Rule update API now do upsert (breaking change)
- Rule update (both update API and partial import API) will check version, only do update when version is newer
- init.json can use to migrate rules preset, also check version for preset migration

feat(rule): rule upsert & init rule migration

---

extensions/sources/kafka/kafka.json

The incorrect structure of Kafka. json properties prevents ekuiper manager from adding sources correctly

fix(kafka): fix incorrect properties structure

---

internal/server/server.go

Removed an unnecessary nil check for the channel reference in the Close method. Simplifies the code logic while maintaining its intended functionality.

refactor(server): do not catch fatal sigs

---

etc/kuiper.yaml
internal/server/pprof_init.go
internal/server/rest.go
internal/server/rule_init.go
internal/server/server.go
internal/server/server_test.go
internal/topo/context/default.go
internal/topo/context/default_test.go
metrics/metrics.go
pkg/model/conf.go

Replaced the `rule_cpu_usage` gauge metric with a new counter metric `rule_cpu_time_seconds_total`, which accumulates total CPU time per rule.
This enables Prometheus to use functions like increase() to calculate the processing time of each rule over a recent period, and to easily compute the CPU usage share of each rule.
Run ekuiper and use [test tool](https://github.com/Yisaer/kuiper-nexmark-test) as shown below:
You can observe rule_cpu_time_seconds_total in prometheus as shown below:
The CPU usage time of each rule within the first 30 seconds as shown below:

feat(metrics): support rule cpu usage counter

---

extensions/sources/kafka/kafka.json

My apologies, I mistakenly confused the JSON structure between Kafka source and Kafka sink in [PR].(https://github.com/lf-edge/ekuiper/pull/3686)
Just patched this - my bad for mixing up the source/sink JSON formats earlier.

fix(kafka): fix kafka source properties bug

---

internal/io/mqtt/source.go
internal/topo/planner/planner_source.go
internal/topo/planner/planner_source_test.go

Only share conn if it must, like neuron stream

fix(planner): strict share conn

---

internal/pkg/store/sql/sqlTs.go

https://github.com/lf-edge/ekuiper/blob/163809ee5191827223759fd820883a361ba3d274/internal/pkg/store/sql/sqlTs.go#L163-L163
fix the issue, the SQL query should be constructed using parameterized queries or prepared statements. However, since SQL drivers typically do not allow parameterized table names, the `table` parameter must be validated explicitly to ensure it contains only safe characters (e.g., alphanumeric characters and underscores). This validation should be implemented in the `isValidTableName` function. additionally, the `getLast` function should avoid constructing the query string dynamically. Instead, it should use a safe and validated table name.
If a database query (such as an SQL or NoSQL query) is built from user-provided data without sufficient sanitization, a malicious …

fix(kv): prepare ts query

---

internal/converter/ext_mock_test.go
internal/schema/registry.go

User should use pre-defined schema id. For backward compatibility, we still support path as schema id.

fix(schema): compatible with path schema id

---

pkg/ast/sourceStmt.go
pkg/ast/sourceStmt_test.go

Allow to not specify type in the external schema. Because some schema does not have type information

feat(schema): allow any type
